lightninglabs/taproot-assets

Makefile
tarodb/mssmt_test.go

Resolves #149.
Each test includes multiple cases, which share some initial set of nodes and run in parallel. Each call to Insert a node into the DB uses the node's `NodeHash()` as a key. If the NodeHash is unintialized, `NodeHash()` will compute and then cache it. This can cause a race if concurrent tests call `NodeHash()` when the NodeHash was unintialized.
Resolve this by calling `NodeHash()` for each node that is part of the state shared between test cases. CompactedLeafNodes already call `NodeHash()` internally so this is not needed for those nodes.
We also add flakehunting targets in the Makefile to make rare races easier to find in the future.

tarodb: fix data races in unit tests

---

README.md

we require to build lnd with `tags=signrpc walletrpc chainrpc invoicesrpc` same as in the "Getting started" Guide
without the explicit build tags taro failed to connect to lnd
``` 
2022-09-29 20:04:09.162 [INF] CONF: Attempting to establish connection to lnd...
error creating server: unable to connect to lnd node: error checking connected lnd version. at least version "v0.15.99, build tags 'signrpc,walletrpc,chainrpc,invoicesrpc'" is required
```

docs: clarify the necessary build tags for lnd in README/Prerequisites

---

tarofreighter/parcel.go

Fixes a bug where we wouldn't add the fee rather than subtract it from the output, which is what'll actually siphon off those additional fees to miners. Also fixes a log message as well to ensure it's all printed out in sats.

tarofreighter: fix semantic error when accounting for fee delta 

---

asset/mock.go
commitment/split.go
internal/test/helpers.go
itest/assertions.go
proof/append.go
proof/append_test.go
proof/file.go
proof/mint.go
proof/mint_test.go
proof/proof_test.go
proof/verifier.go
tarofreighter/chain_porter.go
tarogarden/custodian.go
taroscript/send_test.go

Fixes https://github.com/lightninglabs/taro/issues/57.
With this commit we change the proof file's format to a proof chain. Every proof is hashed with its previous proof's hash (the first proof will have a zero prev hash) to get to the proof's rolling checksum. That way a file can be read serially, proof-by-proof, without needing to load the full file content into memory. This also allows us to append a proof to an existing file easily, once we have a seekable proof reader that can read just the last proof of a file.

multi: refactor proof file format

---

chanutils/func.go
commitment/asset.go
commitment/commitment_test.go
commitment/taro.go
itest/send_test.go
itest/test_list_on_test.go
rpcserver.go
tarodb/assets_store.go
tarodb/assets_store_test.go
tarodb/sqlite.go
tarodb/sqlite/assets.sql.go
tarodb/sqlite/queries/assets.sql
tarofreighter/chain_porter.go
taroscript/send.go
taroscript/send_test.go

With the itest added in this diff, the tests fail for two reasons:
1. The split commitment root wasn't properly being read from disk.
2. The input asset is being mutated somewhere, so when we went to compute the _old_ root to place the PSBT information, it was already using the new amount/witness, etc, etc.
This commit is a temp workaround to demonstrate that something is being mutated here. By caching the pkScript+root, we capture it as it was read from disk.
Will remove this from draft once I add a proper fix for the mutation (in the send delta pipeline). 
This fixes an issue that would prevent an asset output from properly being spent again after a series of sends that each required a new split.

multi: properly read split commitment roots from disk, eliminate unwarranted input asset mutation 

---

cmd/tarocli/addrs.go
tarodb/addrs.go

We must wrap `math.MaxInt64` calls in `int64()` for rpi/arm/32-bit support, otherwise cross-compilation yields this error:
`cmd/tarocli/addrs.go:144:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)`

Wrap math.MaxInt64 in int64() for 32-bit cross-compilation

---

itest/send_test.go
tarofreighter/parcel.go

The [output](https://docs.lightning.engineering/lightning-network-tools/taro/first-steps#docs-internal-guid-90fc9698-7fff-dc82-4d66-091df08c58a9) from `tarocli assets send` currently has a mistake: 
```
"new_outputs": [
{
"anchor_point": "96a370af09f4ed97f408a9a497df2d7a5b0b53cafba7b23654062307cebc3163:0",
"asset_id": "33644efe039d3569e6bafb07bc8f5959578a909e9c5e1c15949c986c54edbf35",
"script_key": "028055056a70daf83e654a28b640dbf7fa893953f87398a51b7c2021520402a54b",
"amount": "900",
"new_proof_blob": null,
"split_commit_proof": null
},
{
"anchor_point": "96a370af09f4ed97f408a9a497df2d7a5b0b53cafba7b23654062307cebc3163:0",
"asset_id": "33644efe039d3569e6bafb07bc8f5959578a909e9c5e1c15949c986c54edbf35",
"script_key": "028055056a70daf83e654a28b640dbf7fa893953f87398a51b7c2021520402a54b", …
```

SendAsset: Correct receiver output index

---

itest/addrs_test.go
itest/assertions.go
itest/round_trip_send_test.go
itest/send_test.go
itest/test_list_on_test.go
tarofreighter/parcel.go
taroscript/send.go

Spun off of #159.
Fixes multiple issues that caused round-trip (minter->receiver->minter) spends to fail:
1. The input TaroCommitment tree was being mutated when computing new TaroCommitments.
2. The input TaroCommitment tree includes asset leaves with SplitCommitments populated, which does not match the tree used for the actual transfer TX.
For the receiver to spend back to the minter, they need to recompute the pkScript used in the anchor output. Both of these issues caused the pkScript to be computed incorrectly in `inputAnchorPkScript()`. The mismatched pkScript caused transaction broadcast to fail.
The new itest includes a round-trip spend to test this fix.

multi: fix input pkscript construction, add round trip spend test

---

asset/asset.go
commitment/commitment_test.go
commitment/split.go
itest/full_value_split_test.go
itest/test_list_on_test.go
tarodb/sqlite/migrations/000002_assets.up.sql
tarofreighter/chain_porter.go
taroscript/send.go
taroscript/send_test.go
vm/error.go
vm/vm.go
vm/vm_test.go

Addresses #99 and #121. Collectible support will likely be a follow-up PR.
Support full-value splits (no change for sender) via split commitments by defining a NUMs / unspendable key, and requiring that key for zero-value root splits.
TODOs:

multi: support non-interactive full-value sends

---

cmd/tarocli/addrs.go
rpcperms/interceptor.go
tarodb/assets_store_test.go

Fixes a few formatting errors, that also could have the linter failing.

multi: run make fmt

---

README.md

remove 🍠  emoji from commands to make them easier to copy and paste, (🍠 command not found error)

update readme: remove 🍠  emoji from commands

---

commitment/asset.go
commitment/commitment_test.go
tarodb/asset_minting.go
tarodb/assets_common.go
tarodb/assets_store_test.go
tarodb/sqlite/assets.sql.go
tarodb/sqlite/migrations/000002_assets.up.sql
tarodb/sqlite/querier.go
tarodb/sqlite/queries/assets.sql
tarofreighter/chain_porter.go
tarofreighter/parcel.go

In this commit we fix a bug that would cause all assets (that matched the other predicates) to be returned when we issue a query that attempts to filter based on just key family. This was due to the `LEFT JOIN` usage in the main query. Before this fix, this meant that all other assets that matched up to that point would be returned in addition to the ones that matched the key family fitler. 
To fix this, we move the filtering into the `WHERE` clause which ensures we only get the precise results we need. Along the way we've added some more debugging context to errors, and also added new test cases to exercise the fixes added.

tarodb: fix bug in asset coin selection related to key families 

---

address/encoding.go
address/records.go
asset/asset_test.go
asset/encoding.go
asset/records.go
proof/records.go

Spinoff of #176.
Currently public keys are sometimes (such as in addresses) unconditionally encoded with an even parity. If that key actually has odd parity, and is already stored, then key upserts behave incorrectly, causing other issues.
To resolve this, we migrate all key encoding & decoding away from the x-only format to the compressed format. This adds a few bytes to the size of some types when encoded, but other techniques can be used to compactly repesented key parity for those types.
Requires BIP updates.

multi: encode/decode keys with their parity byte

---

rpcserver.go
tarodb/asset_minting.go
tarodb/asset_minting_test.go
tarodb/assets_store.go
tarodb/assets_store_test.go
tarodb/sqlite/assets.sql.go
tarodb/sqlite/migrations/000002_assets.up.sql
tarodb/sqlite/models.go
tarodb/sqlite/queries/assets.sql
tarodb/sqlite/queries/transfers.sql
tarodb/sqlite/transfers.sql.go
tarofreighter/chain_porter.go
tarofreighter/interface.go
tarofreighter/parcel.go
tarogarden/caretaker.go
tarogarden/interface.go

Store how much we spent in on-chain fee for minting/transfers operations.
Fixes #144 
Affects #177

tarodb: add `chain_fees` to `chain_txns`

---

commitment/commitment_test.go
commitment/split.go
itest/collectible_split_test.go
itest/test_list_on_test.go
tarofreighter/chain_porter.go
taroscript/send.go
taroscript/send_test.go
vm/error.go
vm/vm.go
vm/vm_test.go

Depends on #159, addresses #99 and #121.
Adds support for non-interactive sends of collectibles by allowing splits bearing collectibles, iff they have an unspendable root and exactly one non-root locator.
Fixes https://github.com/lightninglabs/taro/issues/99 
Fixes https://github.com/lightninglabs/taro/issues/121

multi: support non-interactive collectible sends

---

chanutils/concurrency.go
chanutils/concurrency_test.go
proof/archive.go

In this commit, we simplify the type params a bit by using a new function type def, and eliminating an extra type params. We also swap the order of the last two args (func closure now last), as the next version allows for syntax like:
```
type Ctx context.Context
err := chanutils.ErrGroup(ctx, links, func(ctx Ctx, link string) error {
return WebSrape(link)
})
```

chanutils: simplify type params for ErrGroup

---

tarocfg/config.go

Addresses https://github.com/lightninglabs/taro/issues/204 by removing short flags while the project is still young- people don't yet have all sorts of scripts with hardcoded flags.  
Delete if unwanted. If so I'll just maintain a fork for my own purposes.

Remove short flags

---

tarocfg/config.go

Since the logger most likely won't be initialized in the error case,
trying to use it would cause a panic.

tarocfg: check cfgLogger for nilness

---

README.md

A small change to make the new API docs visible alongside the Builder's Guide resources.

add links to API documentation and guides to README.md

---

tarocfg/server.go
tarogarden/planter.go
tarogarden/planter_test.go

Fixes a bug discovered in #212 where the minting batch ticker was never started when `tarod` was started.
Adds a planter test that relies on the ticker instead of forcing a batch.
Have verified the ticker working with `tarod` outside of itest and unit tests.

Minting timer fix

---

Makefile
go.mod
go.sum
itest/addrs_test.go
itest/aperture.go
itest/assets_test.go
itest/collectible_split_test.go
itest/full_value_split_test.go
itest/integration_test.go
itest/round_trip_send_test.go
itest/send_test.go
itest/tarod_harness.go
itest/test_harness.go
itest/test_list_on_test.go
proof/courier.go
tarocfg/config.go
tarocfg/server.go

This PR adds a local aperture service to the integration test framework. The aperture service is used by taro (via the hashmail system) to transfer proofs during asset transfers.

Add local aperture service to itest

---

commitment/asset.go
commitment/commitment_test.go
tarofreighter/parcel.go
taroscript/send.go
taroscript/send_test.go

This change is a simple refactor which splits the asset commitment `Update` method into `Upsert` and `Delete` methods. The goal here is to make the code easier to read which will help when working on issues such as https://github.com/lightninglabs/taro/issues/241
This PR doesn't block any other PR or issue.

Cleanup asset commitment method names

---

commitment/commitment_test.go
commitment/taro.go
tarofreighter/parcel.go
taroscript/send.go
taroscript/send_test.go

This change is a simple refactor which splits the taro commitment `Update` method into `Upsert` and `Delete` methods. The goal here is to make the code easier to read which will help when working on issues such as https://github.com/lightninglabs/taro/issues/241
This PR doesn't block any other PR or issue.

Cleanup taro commitment method names

---

.github/workflows/main.yaml

In this commit, we activate the merge queue by using the new `merge_group` selector. Without this, the CI won't report back the progress of a CI run to the merge queue, so things won't get auto merged.

build: use the new merge_group selector for the merge queue

---

server.go
tarocfg/server.go

The `NewServer` function signature is `func(cfg *Config) (*Server, error)` but the error is always `nil`. Even in other projects like `loop`, `pool` or `lnd` we did not find a case were an error needed to be returned.
We can delete it from the signature from now and add it in the future (or in a wrapped function) if needed.

server: stop returning an error that is always nil

---

go.mod
go.sum
tapcfg/config.go

This PR adds signet support to tapd.
I tested it with a mint on default signet https://mempool.space/signet/tx/b67eb166b5cb891cc20f11f594114e97da1a61c675cbd439eeeec7664f191fb8
fixes #283

Add Signet support

---

itest/integration_test.go
itest/send_test.go
itest/tapd_harness.go
itest/test_harness.go
itest/test_list_on_test.go
proof/aperture.go
proof/courier.go

This commit adds a new proof courier harness interface which will allow the integration tests to support multiple different proof courier service types. It also ensures that each test case has its own proof courier service instance.
This commit also removes the need to specify a proof courier when starting a new taro node during a test case. By default, the test harness will be inspected for an existing proof courier.

itest: support multiple proof courier service types

---

tapcfg/config.go

Updates the port in the default testnet universe federation server address. The server will support both ports for a while until this change has been released with a proper version for a while.

tapcfg: update default testnet universe port

---

tapdb/postgres.go
tapdb/sqlite.go

The default is unlimited, means that with the default postgres limit of 100, you'll run into errors.

tapdb: properly set max connections for postgres

---

tapdb/interfaces.go
tapdb/sqlerrors.go

In this commit, we start to use the serializable snapshot isolation by default for postgres. For sqlite, this is a noop as only a single writer is allowed at any time. With this mode, we should guard against all types of anomalies, at the cost of extra locking and potential perf hits.
One thing we'll need to test out is if the DB driver will automatically do retries or not if a transaction cannot be serialized.
This is an attempt at fixing #333 at a global level.

tapdb: use the serializable isolation by default for postgres

---

address/address.go
address/address_test.go
tapdb/addrs.go

This commit clarifies that the version information currently stored in the tap address relates to the asset version and not to the address version.

address+tapdb: rename field: Tap.Version -> Tap.AssetVersion

---

cmd/tapcli/universe.go
itest/assertions.go
itest/universe_test.go
rpcserver.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go
universe/auto_syncer.go
universe/interface.go

Display 33-byte script keys instead of 32 bytes. We should audit the current structs are parsing to make it internally consistent, so that copy & paste works on the CLI.

universe: RPC fixes

---

itest/send_test.go
itest/test_list_on_test.go

This aim of this change is just to make it clear that an address can be re-used for multiple send events.

itest: basic send test re-uses the same recv address for multiple sends

---

itest/assertions.go
itest/integration_test.go
itest/send_test.go
itest/test_list_on_test.go

This PR adds an itest which ensure that we resume the send procedure which was interrupted by a tapd restart.

itest: resume pending package send

---

itest/send_test.go

Following on from this comment: https://github.com/lightninglabs/taproot-assets/pull/365#discussion_r1232126210

itest: fix for-loop indexing

---

itest/addrs_test.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/mssmt.sql.go
tapdb/sqlc/queries/assets.sql
tapdb/sqlc/queries/mssmt.sql

Fixes https://github.com/lightninglabs/taproot-assets/issues/368.
As @habibitcoin already correctly identified, one of our SQL queries is incorrect and overwrites valid meta information with `NULL` when importing a proof.

Asset metadata overwrite fix

---

tapcfg/config.go

In this commit, we fix a bug that would cause the logs to always go to the default log location even if a different base dir was set. Before this commit, we'd create the log rotators before the call to `ValidateConfig`, which is where we modify the log dir location to be relative to the final base dir.
The fix here is simple: create the log rotator _after_ the config has been validated.

tapcfg: ensure log rotator created after config validation

---

version.go

First step to releasing v0.2.1.
Verified with `tapcli-debug -v`.

version: bump version to v0.2.1-alpha

---

.github/workflows/main.yaml
Dockerfile
dev.Dockerfile
make/builder.Dockerfile
proof/aperture.go

In this commit, we fix a test harness config value that overflowed. We also bump the golang version used in all docker images to 1.20.5.

multi: fix aperture config + bump golang version

---

.github/workflows/main.yaml
Dockerfile
dev.Dockerfile
itest/aperture_harness.go
itest/tapd_harness.go
itest/test_harness.go
make/builder.Dockerfile
taprpc/Dockerfile
tools/Dockerfile
version.go

Replaces https://github.com/lightninglabs/taproot-assets/pull/377.
Adds some Golang version bumps that were missed in https://github.com/lightninglabs/taproot-assets/pull/375 and updates the comments on what files such a bump needs to update.
Also makes sure that we catch release compilation issues early by running the release build in CI.
Since there was already a tag pushed for `v0.2.1-alpha`, we need to bump the version to `v0.2.2-alpha`.

Fix multiple small issues with release, prepare for 0.2.2-alpha

---

scripts/release.sh

Addresses some build reproducibility issues discovered during the release process for v0.2.2. Builders may have `GOAMD64` set locally, which would lead them to build different binaries for 64-bit machines.
This PR also includes some fixes for warnings flagged by shellcheck.
This fix was tested by changing the `GOAMD64" env. var. locally and re-building.

script: pin GOAMD64 for release builds

---

.github/ISSUE_TEMPLATE/issue-template--updated-from-lnd.md

When clicking "New Issue", the copy in the label referenced lnd which is confusing given expectations are to create a taproot-assets issue

Remove lnd references in user-visible issue copy

---

perms/perms.go

This PR adds the `QueryAssetStats` and `UniverseStats` endpoints to the macaroon whitelist so that they can be accessed without authentication.

QueryAssetStats and UniverseStats no auth client access

---

chain_bridge.go
itest/assertions.go
proof/mock.go
proof/proof_test.go
proof/verifier.go
tapfreighter/chain_porter.go
tapgarden/caretaker.go
tapgarden/interface.go
tapgarden/mock.go

Closes https://github.com/lightninglabs/taproot-assets/issues/387

Add proof block height verification

---

itest/assertions.go
rpcserver.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/407.

rpcserver: add missing merkle root and tapscript sibling fields to DecodeProof RPC

---

version.go

After https://github.com/lightninglabs/taproot-assets/pull/408 is merged through the merge queue, we'll want to release `v0.2.3-alpha`.

version: bump version to v0.2.3-alpha

---

taprpc/taprootassets.proto
taprpc/taprootassets.swagger.json
taprpc/taprootassets_grpc.pb.go

The API docs generator failed because `tarocli` no longer is a valid command.
Fixes https://github.com/lightninglabs/lightning-api-ng/issues/21.

taprpc: fix api docs generator hint

---

cmd/tapcli/universe.go

I forgot to add a CLI subcommand for the `Info` RPC. This fixes another bug in the API docs generation.

cmd/tapcli: add universe info sub command

---

tapdb/universe.go
tapdb/universe_forest.go
tapdb/universe_test.go

Preliminary refactor PR made in an attempt to split up the work a bit.

Preliminary refactor in preparation for adding multiverse support

---

.github/workflows/docker.yml

Requires us to set the following two GitHub repository secrets:
```
DOCKER_USERNAME
DOCKER_API_KEY
```

GitHub: add automated docker build on tag push

---

tappsbt/address.go
tappsbt/mock.go
tappsbt/testdata/psbt_encoding_generated.json

The address already contains the internal key as a compressed (33-byte) public key. But the test vectors were incorrectly using the x-only (32-byte) representation of the internal key, which lead to an incorrect stripping of the parity byte in the wrong place, which this PR now fixes.

tappsbt: fix incorrect test vectors

---

address/address.go
address/book.go
address/encoding.go
address/mock.go
address/records.go
rpcserver.go
tapdb/addrs.go
tapgarden/custodian_test.go
tappsbt/decode_test.go
taprpc/taprootassets.pb.go
taprpc/taprootassets.proto
taprpc/taprootassets.swagger.json

Major change in this PR is that the proof courier addr field in the Tap address structure is no longer a pointer. I think this change makes sense because the field is mandatory and should never be `nil`.
Created this PR to address these review comments: https://github.com/lightninglabs/taproot-assets/pull/450#pullrequestreview-1588024716 and https://github.com/lightninglabs/taproot-assets/pull/450#pullrequestreview-1588020864

Cleanup proof courier addr

---

itest/addrs_test.go
itest/assertions.go
itest/assets_test.go
itest/collectible_split_test.go
itest/full_value_split_test.go
itest/interface.go
itest/mint_batch_stress_test.go
itest/multi_asset_group_test.go
itest/psbt_test.go
itest/re-issuance_test.go
itest/re-org_test.go
itest/round_trip_send_test.go
itest/send_test.go
itest/test_harness.go
itest/universe_test.go

In the first commit we make most of the checks used in the itest able to work with tapd/go testing primitives (like rpc clients and `*testing.T` structs) instead of depending on `testHarness`. That will allow us use those methods in tests that do not involve tapd harness but external tapd processes.
In the second commit we inject all the rpc clients and chain functionalities that it needs to operate so it does not depend on our itest suite and can be executed against real instances.
Part of #433

itest: abstract the mint batch stress test 

---

itest/aperture_harness.go
itest/tapd_harness.go
proof/courier.go
rpcserver.go
tapcfg/server.go
tapdb/assets_store.go
tapdb/sqlc/migrations/000005_transfers.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/transfers.sql
tapdb/sqlc/transfers.sql.go
tapfreighter/chain_porter.go
tapfreighter/interface.go
tapfreighter/parcel.go
tapfreighter/wallet.go
tapgarden/custodian.go
tappsbt/address.go
tappsbt/decode_test.go

This PR includes changes which allow us to persist a proof courier address for use in resuming a pending package's send process.
Fixes #446

Chain porter proof courier service initialised using configurable address

---

itest/send_test.go
itest/tapd_harness.go
proof/courier.go
proof/proof.go
tapgarden/custodian.go

Replaces https://github.com/lightninglabs/taproot-assets/pull/483.
We noticed that the hashmail proof courier didn't work properly in the integration tests (while working on the new RPC based courier).
This PR fixes two issues that lead to the hashmail proof courier not working correctly in the itest:
- One test sends to the same TAP address multiple times, but the custodian only ever looked at one and then bailed out (because we didn't delete completed events, kudos to @ffranr for finding this).
- The hashmail courier looks at previous send attempts and then goes into a backoff wait if the same proof (or at least what looks like the same proof because it has the same script key and asset ID because it's two different transfers to the same address). That backoff time was simply longer …

Fix proof courier in integration test

---

itest/tapd_harness.go
itest/test_harness.go
itest/test_list_on_test.go
proof/courier.go
tapcfg/config.go
tapcfg/server.go

Aperture is the service. The courier type enum should organise supported courier address protocols.

Rename aperture courier type to hashmail courier type

---

proof/courier.go
tapfreighter/chain_porter.go
tapfreighter/parcel.go

This PR closes issue https://github.com/lightninglabs/taproot-assets/issues/455 .

tapfreighter: validate proof courier address before commencing send

---

asset/asset.go
cmd/tapcli/universe.go
itest/send_test.go
itest/tapd_harness.go
itest/test_harness.go
itest/test_list_on_test.go
itest/universerpc_harness.go
proof/archive.go
proof/courier.go
proof/proof.go
rpcserver.go
tapdb/assets_store_test.go
tapfreighter/chain_porter.go
tapgarden/custodian.go
taprpc/marshal.go
taprpc/universerpc/marshal.go
universe/base.go

This PR adds a new multiverse RPC proof service handle for use in the chain porter.
This PR should close these issues when merged:
* https://github.com/lightninglabs/taproot-assets/issues/439
* https://github.com/lightninglabs/taproot-assets/issues/467
* https://github.com/lightninglabs/taproot-assets/issues/344
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightninglabs/taproot-assets/473)

Add multiverse RPC proof courier

---

address/address.go
address/address_test.go
address/book.go
address/mock.go
address/records.go
address/testdata/address_tlv_encoding_generated.json
tapdb/addrs.go
tapdb/sqlc/addrs.sql.go
tapdb/sqlc/migrations/000003_addrs.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/addrs.sql
tapgarden/custodian_test.go
tapscript/send_test.go

With the recent PR https://github.com/lightninglabs/taproot-assets/pull/501 we changed the asset version within an address into the address' version itself. We still need the asset version in the address as well though, so this commit restores it, including the database storage.
EDIT: This re-orders all taproot address TLV field values to get them nicely incrementing. I'll follow up with a PR to the BIP.

multi: add address version to database

---

proof/fuzz_test.go

Fixes a linting error that found its way onto the `main` branch somehow.

proof: fix unnecessary trailing newline

---

tapgarden/seedling.go

This commit removes a TODO which is already satisfied. The checks are already enforced on the DB level.

tapgarden: enhance Seedling.validateFields() doc and remove TODO

---

config.go
itest/tapd_harness.go
tapcfg/server.go
tapdb/multiverse.go
tapdb/universe_test.go
universe/base.go
universe/interface.go

This PR renames multiverse store and archive method names to reflect the fact that they are now handle transfer proofs in addition to issuance proofs.
We should merge https://github.com/lightninglabs/taproot-assets/pull/473 first.

Generalise multiverse method names to support all proofs.

---

universe/auto_syncer.go

In this commit, we fix a bug that would cause universe proof push to fail for all servers, if anyone of them was unreachable, or rejected the proof.
If we return `err` here, then eventually the context will be read by other goroutines, which is already cancelled at this point. This'll cause the push attempt to stop short.
We now long and return `nil` so the other goroutines will continue.
See https://github.com/lightninglabs/taproot-assets/issues/527 for more details.

universe: update pushProofToFederation to make sure all servers are tried

---

proof/archive.go
tapdb/assets_store.go
tapfreighter/chain_porter.go

Closes https://github.com/lightninglabs/taproot-assets/issues/508
This PR fixes the initial state of the proof courier's backoff procedure. Before this change, the initial state of the backoff procedure would erroneously include the previous send event(s). The fix involves using the outpoint to distinguish between send events.

Backoff procedure erroneously resumed between two different send events

---

rpcserver.go
tapdb/multiverse.go
tapdb/universe.go
tapdb/universe_stats.go
tapdb/universe_stats_test.go
tapdb/universe_test.go
tapgarden/caretaker.go
tapgarden/planter.go
universe/auto_syncer.go
universe/base.go
universe/interface.go
universe/syncer.go
universe_rpc_diff.go
universe_rpc_registrar.go

In this PR we change instances of "minting", "base", and "issuance" to more general terminology which will clarify that the code is also used for transition proofs (non-issuance).
Associated issue: https://github.com/lightninglabs/taproot-assets/issues/535
I may create additional PRs so I don't necessarily want this PR to close the above issue.

Generalise universe structs/methods/variables to support transfer proofs in addition to issuance proofs

---

tapgarden/caretaker.go

This also fixes a bug in `GenRawGroupAnchorVerifier` where the `groupAnchor` value wasn't being properly re assigned.

tapgarden: use lru.Cache for various new group caches

---

address/event.go
rpcserver.go
tapdb/addrs.go
tapdb/asset_minting.go
tapdb/asset_minting_test.go
tapdb/assets_common.go
tapdb/assets_store.go
tapdb/interfaces_test.go
tapdb/postgres.go
tapdb/sqlc/addrs.sql.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/migrations/000002_assets.up.sql
tapdb/sqlc/migrations/000003_addrs.up.sql
tapdb/sqlc/migrations/000005_transfers.up.sql
tapdb/sqlc/migrations/000006_addr_event.up.sql
tapdb/sqlc/migrations/000007_universe.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/querier.go
tapdb/sqlc/transfers.sql.go
tapdb/sqlc/universe.sql.go
tapdb/sqlite.go
tapdb/sqlutils.go
tapdb/universe.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go
tapgarden/interface.go
universe/interface.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/533.

Use 64bit primary keys in DB

---

tapdb/universe_stats.go
tapdb/universe_stats_test.go

Closes https://github.com/lightninglabs/taproot-assets/issues/541
I have confirmed that the failing unit test now passes.
I think we should enforce UTC location in `clock.NewTestClock` (LND). Thoughts on this @guggero ?

Fix instances of `time.Now()` which should be set to UTC

---

.gitignore
itest/assertions.go
itest/loadtest/mint_batch_test.go
itest/mint_batch_stress_test.go
itest/utils.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/539.
This PR allows the load test to be run against both `btcd` and `bitcoind` and also makes it ready for being run multiple times in a row against the same node.
cc @calvinrzachman

loadtest: prepare for multiple consecutive runs

---

itest/loadtest/config.go
itest/loadtest/load_test.go
itest/loadtest/mint_batch_test.go
itest/loadtest/send_test.go
itest/loadtest/utils.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/469.
Depends on https://github.com/lightninglabs/taproot-assets/pull/556.
This is the last piece to address our initial requirements for the load test.
cc @calvinrzachman:
I changed some things around and it's now possible to either specify a test case in the config (`test-case=xxx`, if you don't specify anything, all two tests will run) or in the command line (`-test.run="TestPerformance/send"`).
There are a couple of new test specific settings we can specify (and I renamed the `batch-size` config to `mint-test-batch-size`).
Here are the default values for these new config values:
```
mint-test-batch-size=200
send-test-num-sends=50
send-test-num-assets=1
send-test-send-type=1
```

loadtest: add multi send test

---

tapdb/universe_test.go

In this commit, we add a test for the universe leaf overflow. This tests that if we try to register a leaf that'll overflow the tree, then we'll just return an error and bail out of the transaction.

tapdb: add unit test for universe leaf overflow

---

rpcserver.go

In this commit, we stop trying to strictly parse the meta field. Instead, users can set it to w/e they want, with the default being opaque. This lets users start to add structure to the meta field from day one. One example is a set meta with fields that dictate how the asset unit is to be displayed. This can be used to do things like leverage the current fix point format to add decimal places for display.

rpc: unconstrain meta field for MintAssets

---

cmd/tapcli/universe.go
itest/loadtest/mint_batch_test.go
itest/mint_batch_stress_test.go
rpcserver.go
tapdb/sqlc/migrations/000007_universe.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/universe.sql
tapdb/sqlc/universe.sql.go
tapdb/universe_stats.go

Depends on https://github.com/lightninglabs/taproot-assets/pull/540 . Do not merge this PR before merging https://github.com/lightninglabs/taproot-assets/pull/540 I've converted this PR to draft until all parent PRs have been merged.
This PR adds universe identity proof type support to universe events stats database SQL statements.

Universe events stats handle universe identity proof type

---

tapfreighter/wallet.go
tapgarden/caretaker.go

Fixes #538.
Adds sanity checks for signed TXs, before TX broadcast, to allow for more complete unwinding of a mint or send.

tapfreighter+tapgarden: prevent fee overpayment

---

cmd/tapcli/main.go
tapcfg/config.go
tapcfg/server.go
version.go

Depends on https://github.com/lightninglabs/taproot-assets/pull/564 for universe proofs to be synced.

tapcfg: allow using mainnet, enable universe proof courier by default

---

make/release_flags.mk

The official docker image and binary release build should have the Prometheus monitoring capability built in by default. We enable that by adding the `monitoring` tag to the list of release build tags.

make: enable monitoring build tag by default for release builds

---

README.md
docs/safety.md

Implements the first part of https://github.com/lightninglabs/taproot-assets/issues/426.
This commit updates the README to mention mainnet usage in `v0.3.0-alpha` and introduces a new Taproot Assets Operational Safety Guidelines document.

docs+README: add mainnet safety guidelines

---

cmd/tapcli/universe.go
tapcfg/config.go
tapcfg/server.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go

When we made testnet the default, the default config logic wasn't updated to properly implement the fallback logic. As a result, on testnet, the mainnet courier was still being used.

tapcfg: fix defaults for testnet universe courier

---

cmd/tapcli/universe.go
fn/iter.go
rpcserver.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/566.
In draft as still needs some manual testing.
Would also like to add a universe federation config info command before merge.
Intended supported usage would be to set the insert or export bools independently (one or both at the same time), and only modify the config for a single scope at a time (global config or config for a specific asset).

tapcli: expose universe sync config settings

---

tapdb/multiverse.go
tapdb/universe_test.go

In this commit, we fix an issue that prevented the display of asset IDs for asset group members. The unpopulated proof type field led the following query for universe leaves to fail.

tapdb: populate proof type when fetching uni roots

---

tapdb/sqlc/migrations/000009_universe_configs.down.sql
tapdb/sqlc/migrations/000009_universe_configs.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/universe.sql
tapdb/sqlc/universe.sql.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go

Fixes multiple issues with sync config load and store.
The first issue was the federation DB handle not returning the correct global config when the global config is modified for one proof type - this is resolved by loading the default config, and keying configs by proof type. Configs read from the DB then replace the default config with the matching proof type.
The second issue affected grouped assets, and led to group member asset IDs not being shown on the CLI.
The third issue was the UNIQUE constraint on universe sync configs not being enforced, since NULL values are distinct in UNIQUE constraints by default for SQLite and Postgres. This could lead to a bad configuration state with multiple entries for the same universe. This behavior is not configurable for SQLite, so extra columns …

tapdb: Federation DB fixes

---

cmd/tapcli/universe.go
itest/burn_test.go
itest/collectible_split_test.go
itest/loadtest/send_test.go
itest/tapd_harness.go
itest/test_list_on_test.go
itest/utils.go
proof/courier.go
rpcserver.go
tapdb/sqlc/queries/transfers.sql
tapdb/sqlc/transfers.sql.go
tapfreighter/wallet.go
tapgarden/custodian.go
tapscript/send.go
tapscript/tx.go
universe/base.go
universe/syncer.go
vm/vm.go

This is a collection of bug fixes and the corresponding integration tests that discovered them.
Depends on https://github.com/lightninglabs/taproot-assets/pull/592.
Fixes https://github.com/lightninglabs/taproot-assets/issues/582.
Fixes https://github.com/lightninglabs/taproot-assets/issues/571.
Fixes https://github.com/lightninglabs/taproot-assets/issues/593.

Multiple fixes around commitments and group keys

---

.gitignore
Makefile
make/testing_flags.mk
vm/testdata/vm_validation_generated.json
vm/testdata/vm_validation_generated_error_cases.json
vm/vm.go
vm/vm_test.go

Spinoff of #549.
Improves test coverage for the VM and ports Makefile improvements from LND that allow for measuring test coverage per-package and per-test-case.

make+vm: increase vm test coverage, improve the coverage target

---

tapfreighter/chain_porter.go

We forgot to exclude burn outputs when it comes to burns, which then resulted in the `invalid proof courier URI address: parse "": empty url` error, failing to confirm burns.
So the transfer was pending forever.
Fixes https://github.com/lightninglabs/taproot-assets/pull/599.

tapfreighter: don't attempt to send burns with courier

---

universe/syncer.go

In this commit, we cut down on the logging a no-op Universe sync needs. This cuts down on logs like:
```
2023-10-18 21:25:09.117 [INF] UNIV: Root for issuance-b14a8563de6112f7bb6c57f90eb0d84abcd745c32625a28d42467799dbf5294f matches, no sync needed
2023-10-18 21:25:09.118 [INF] UNIV: Root for issuance-a5b2e79a2b8668b5bd881331b13b44925a8ea0ce7a0b96bf319582c7ef133605 matches, no sync needed
2023-10-18 21:25:09.118 [INF] UNIV: Root for issuance-e455f0b659e9cf011cf070e330b2e9f12016dc2bae6010dacc490c4402fb6a8c matches, no sync needed
2023-10-18 21:25:09.119 [INF] UNIV: Root for issuance-787b019ce84cf262577a586dc131891db176bd066f97dbe5b31805a432f22dda matches, no sync needed
2023-10-18 21:25:09.119 [INF] UNIV: Root for issuance-bc810dbd27b8d12e9bdfaae391aaaf69afb637607e6037a27a7160dece013ac9 …
```

universe: use debug logging when no sync needed

---

tapdb/postgres.go
tapdb/sqlite.go

We want to be able to specify the number of idle connections, and other lifetime parameters for Postgres as well.

tapd: allow configuring all connection params for Postgres

---

tapdb/universe_federation.go
universe/syncer.go

If a target set of universes is not specified the syncer will now sync universes which have associated specific sync configs, instead of all known universes.
Fixes https://github.com/lightninglabs/taproot-assets/issues/618

universe: stop syncer from syncing all known universes by default

---

itest/send_test.go
itest/tapd_harness.go
itest/test_list_on_test.go
proof/courier.go

This PR extracts the backoff procedure from the hashmail proof courier and makes use of it in the universe RPC proof courier.
Fixes https://github.com/lightninglabs/taproot-assets/issues/512

Add backoff procedure to universe RPC proof courier

---

fn/func.go
itest/loadtest/mint_batch_test.go
tapdb/sqlc/migrations/000010_universe_stats.down.sql
tapdb/sqlc/migrations/000010_universe_stats.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/universe.sql
tapdb/sqlc/universe.sql.go

This fixes a bug where the output of `tapcli universe stats assets` would show weird duplicates because the query would also include transfer related universe roots.
This also fixes the load test to work with the latest version of the `main` branch.

universe stats: only select issuance roots for asset related stats

---

address/book.go
address/log.go
config.go
itest/addrs_test.go
itest/tapd_harness.go
itest/test_harness.go
itest/test_list_on_test.go
itest/universe_test.go
itest/universerpc_harness.go
log.go
rpcserver.go
tapcfg/config.go
tapcfg/server.go
tapgarden/custodian_test.go
tapgarden/mock.go
universe/auto_syncer.go

Fixes #620.
This PR adds support for creating addresses for assets that  a node has not bootstrapped or synced. If the asset info is not found, the node tries to sync asset info from all members of their universe federation. If the asset info is found, this asset is also added to the universe sync config to keep track of future possible issuance.
This helps address the UX changes from switching global sync to opt-in, since you can also make an address for an asset that's a member of an asset group, without having bootstrapped the asset group creation itself.
A related change is that the `QueryAssetRoots` RPC will now try and look up an asset group for a given universe ID, iff the ID specified an asset ID and no other roots were found. This is what allows a user to bootstrap an asset group …

address: optimistic asset sync

---

itest/send_test.go
itest/universerpc_harness.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/638
Before the changes introduced in this PR, the universe proof courier proof retrieval itest did not ensure that the proof was actually retrievable after multiple retrieval attempts were conducted. This PR ensures that the proof can actually be retrieved after repeated retrieval attempts using the backoff procedure.
This PR is ready for review.

Ensure receiver node backoff retries finally succeed in asset send via universe proof courier

---

tapdb/multiverse.go
tapdb/universe_stats.go

In this commit, we fix a bug that would cause the universe stats cache to be wiped more than once every 30 minutes. Before this commit, we'd accumulate a new background `time.AfterFunc` ticker for each unique request set in the cache.
To fix this, we'll always first stop the old ticker before making a new one.

tapdb: ensure universe asset stats ticker is stopped before refresh

---

taprpc/taprootassets.pb.gw.go
taprpc/taprootassets.swagger.json
taprpc/taprootassets.yaml

Fixes https://github.com/lightninglabs/taproot-assets/issues/668

taprpc: change getinfo REST endpoint from POST to GET

---

chain_bridge.go
go.mod
go.sum

Fixes #315 , #613 . Depends on https://github.com/lightninglabs/lndclient/pull/161 .
This makes use of the `GetBlockHeader` RPC now available in LND v0.17.1 to avoid fetching a full block during proof verification.
`VerifyBlock` is used in the `HeaderVerifier`, which never made use of the full block. This should be safe to change for all places where a `HeaderVerifier` is used, so this is added without adding a separate implementation of `HeaderVerifier`.
Confirmed that the `GetBlock` calls are no longer made by running `tapd` with this PR backed by LND v0.17.1-beta-rc1 and manually syncing.

chain_bridge: fetch block headers over blocks when verifying proofs

---

universe/auto_syncer.go
universe/base.go

In this commit, we fix a bug that would cause a log entry to be garbled when we try to sync with a Universe, but it fails. Before this commit, we used `%w`, which should only be used when _creating_ a new error, not logging one.

universe: fix log entry when sync fails

---

.github/workflows/release.yaml

The latest tag hit this error in the final phase of the build:
>  tapd-v0.3.2-beta.rc1/* not include valid file.
The actual release artefacts use the package name which is `taproot-assets` and not `tapd. So in this commit, we attempt to point it to the proper location in the work directory.

build: fix github actions to ensure release artefacts are uploaded

---

tapdb/sqlc/migrations/000002_assets.up.sql
tapdb/sqlc/migrations/000012_anchor_txid.down.sql
tapdb/sqlc/migrations/000012_anchor_txid.up.sql

Drop and re-create genesis_info_view

---

cmd/tapcli/assets.go
cmd/tapcli/universe.go
taprpc/assetwalletrpc/assetwallet.proto
taprpc/assetwalletrpc/assetwallet.swagger.json
taprpc/assetwalletrpc/assetwallet_grpc.pb.go
taprpc/taprootassets.proto
taprpc/taprootassets.swagger.json
taprpc/taprootassets_grpc.pb.go
taprpc/universerpc/universe.proto
taprpc/universerpc/universe.swagger.json
taprpc/universerpc/universe_grpc.pb.go

Adds some missing tags in the proto files that prevented parts of our API docs page from showing CLI commands when one exists.
Right now this page, https://lightning.engineering/api-docs/api/taproot-assets/taproot-assets/fetch-asset-meta , shows no `Shell` example even though the command exists.
Also fixes some help comments.
I don't think we can easily add a lint for these comments since some RPC endpoints intentionally don't have a matching CLI cmd, like the PSBT endpoints.

taprpc: add missing cli autogen docs

---

.github/workflows/release.yaml

Release name should be `Taproot Assets v...` rather than `tapd v...`.

workflows: fix release name

---

itest/tapd_harness.go
itest/test_harness.go
itest/test_list_on_test.go
itest/universe_federation_test.go
rpcserver.go
tapdb/assets_store_test.go
tapdb/sqlc/migrations/000013_universe_fed_proof_sync_log.down.sql
tapdb/sqlc/migrations/000013_universe_fed_proof_sync_log.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/universe.sql
tapdb/sqlc/universe.sql.go
tapdb/sqlite.go
tapdb/sqlutils_test.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go
tapdb/universe_test.go
tapgarden/caretaker.go
universe/auto_syncer.go
universe/interface.go

Closes https://github.com/lightninglabs/taproot-assets/issues/526
This PR adds a new SQL table which logs the federation sync status of select proofs. In this PR we use the new table to log and re-attempt failed asset issuance proof push sync events.
The federation envoy is modified such that tick events kick-off syncing for pending proofs found in the new log table.
I would be happy to receive reviews to double check that I'm on the right track with these changes.
This PR is currently missing tests.

Federation envoy re-attempts sync push for issuance proofs

---

Makefile
fn/func.go
make/testing_flags.mk
tapgarden/caretaker.go
tapgarden/mock.go
tapgarden/planter.go
tapgarden/planter_test.go

Fixes #360 and #562 .
I found a few problems in the caretaker cancellation error reporting and cancellation, which manifested as an intermittent deadlock in the caretaker when running the minter tests under the race detector / with the `unit-race` target. The other test that revealed issues was deliberately causing failures in the caretaker as part of testing fee estimation, but that itest will be in a separate PR.
I verified these fixes locally by running 100 iterations of `TestBatchAssetIssuance` under standard conditions / with `make unit`, and under the race detector / with `make unit-race`.
One possible TODO is adding extra coverage for when the caretaker is cancelled, but I think the existing unit tests already cover the main partitions of before and after `BatchStateBroadcast`.

tapgarden: fix races and deadlocks in caretaker

---

rpcserver.go
tapscript/send.go

This removes some instances of error shadowing, which caught one minor bug where we would have returned a `nil` error after an error was `non-nil`.

rpcserver+tapscript: err shadowing fixes

---

asset/asset.go
asset/asset_test.go
asset/mock.go
commitment/commitment_test.go
go.mod
proof/append_test.go
proof/proof.go
proof/proof_test.go
proof/verifier.go
tapdb/asset_minting_test.go
tapdb/assets_store_test.go
tapscript/mint.go
vm/vm_test.go

Spun out of #549 . Adds a few test cases related to group key handling following the group key derivation algorithm changes and storage changes that were included in 0.3.0. We also remove some clearly-redunant error checking in proof validation.
Coverage for `asset` increases by 3.6% to 70.8%, for `tapdb` an increase of 0.2% to 66.1%, and for `proof` an increase of 0.4% to 56.1%.

misc: group key testing

---

itest/burn_test.go
itest/test_list_on_test.go
rpcserver.go

This PR adds an itest which ensures that we can burn an asset from an asset group in the simplest case.
It makes the following changes to the `BurnAsset` RPC endpoint:
* Adds additional logging.
* Adds missing error handling when attempting to retrieve a group key.
This PR was created in an attempt to re-produce bug https://github.com/lightninglabs/taproot-assets/issues/704

Add asset group burn itest, logging, and missing error handling

---

itest/tapd_harness.go
itest/test_harness.go
tapdb/sqlite.go
tapdb/sqlutils_test.go
tapdb/test_postgres.go
tapdb/test_sqlite.go

This PR will allow us to specify a particular tapd sqlite database file when creating an itest tapd harness or when unit testing our database store functionality. This should help us in debugging tapd. 
This PR was created as part of the work towards solving https://github.com/lightninglabs/taproot-assets/issues/704

Add means to specify sqlite db file path for tapd test harness and db unit tests

---

itest/psbt_test.go
itest/test_list_on_test.go
rpcserver.go
tapscript/send.go

This PR solves https://github.com/lightninglabs/taproot-assets/issues/297 for the case were each input asset ID is the same.
This PR modifies our asset send procedure such that we can spend a multi-input full value PSBT where each input has the same asset ID. The PR adds an itest to test the new changes.
There are more things we should test:
* more than 2 inputs
* sending the received PSBT spend onwards once more.
But lets keep this PR small if we can and open another (if that makes sense).
This PR replaces https://github.com/lightninglabs/taproot-assets/pull/741
I've moved the branch to repo `lightninglabs/taproot-assets` so that I can base another branch on top of it.
Fixes #297

Multi-input PSBT spend for homogeneous input asset ID

---

proof/courier.go
server.go
tapfreighter/chain_porter.go
universe/auto_syncer.go
universe/base.go
universe/interface.go
universe/syncer.go
universe_rpc_diff.go
universe_rpc_registrar.go

On the instance we've run, we've been seeing a very high number of active TCP connections at any given time. After tweaking some Aperture related settings, it seems that the issue is with our own gRPC server, and the way we make outbound connections. 
This PR implements to fixes to attempt to mitigate this issue:
* Close out any outbound connections we make (courier, gRPC syncing, etc) once we're done. 
* Add a default idle timer that'll close out connections that haven't received any requests/responses after an interval of time.

multi: attempt to fix issue of high number of TCP connections by explicitly closing connections and implementing an idle timer

---

itest/send_test.go
itest/tapd_harness.go
proof/courier.go
proof/mock.go
rpcserver.go
tapcfg/config.go
tapcfg/server.go
tapfreighter/chain_porter.go
tapfreighter/parcel.go
tapgarden/custodian.go
tapgarden/custodian_test.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/597.
This PR removes a bunch of TODOs around the way proof couriers are instantiated and receive their configuration.
After the refactor we then fix a bug where we didn't attempt to fetch a proof using a proof courier again after restarting the daemon.

proof courier: general cleanup and refactor, re-try after restart

---

address/address.go
asset/interface.go
asset/mock.go
commitment/commitment_test.go
itest/loadtest/mint_batch_test.go
proof/courier.go
rpcserver.go
tapdb/assets_store_test.go
tapgarden/custodian_test.go
tapgarden/planter_test.go
tappsbt/decode.go

chore: fix typos

---

cmd/tapcli/assets.go
go.mod
itest/assertions.go
itest/burn_test.go
itest/fee_estimation_test.go
itest/psbt_test.go
itest/send_test.go
itest/test_list_on_test.go
itest/utils.go
rpcserver.go
tapfreighter/wallet.go
tapgarden/caretaker.go
tapgarden/mock.go
tapscript/send.go
tapscript/util.go

Fixes #671 
Verifies fixes for various issues with fee estimation.
There are also some issues with cleaning up caretaker state if the caretaker returns an error, which is not recoverable from inside the caretaker.
Batch finalization could be manually reattempted by the user.
Also added extra logging of fee rates and transaction weights.
Should also change units exposed to the user.
> In line with our other software, this flag could be called `--sat_per_vbyte` and be measured in sat/vB. We use the term `fee_rate` a bit differently in LND.

multi: anchor fee test coverage

---

itest/assertions.go
itest/psbt_test.go

This commit extends the existing multi-input PSBT spend test to also include a partial value spend.

itest: extend multi-input PSBT spend test to include partial value spend

---

fn/func.go
fn/iter.go
itest/addrs_test.go
itest/send_test.go
itest/test_list_on_test.go
itest/universe_test.go
proof/archive.go
proof/courier.go
proof/file.go
proof/mint.go
tapcfg/server.go
tapdb/assets_store.go
tapdb/multiverse.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/assets.sql
tapdb/sqlutils_test.go
tapgarden/custodian.go
tapgarden/mock.go
tapgarden/re-org_watcher.go

~Depends on https://github.com/lightninglabs/taproot-assets/pull/712.~
Fixes https://github.com/lightninglabs/taproot-assets/issues/578.
This PR updates the proof notification publish/subscribe mechanism in a way that allows us to pass in multiple proof sources to the custodian so it can detect incoming proofs from multiple sources.

[1/2] custodian: look up proofs in local universe as well

---

tapdb/migrations.go

In this commit, we add support for logging migrations as they happen. This is useful for users to keep track of what happens during a `tapd` update.

tapdb: add support for logging migrations

---

itest/assertions.go
itest/loadtest/send_test.go

As investigated by @calvinrzachman, here's a small fix to make the load test more reliable.
Because things can take a bit longer the more addresses and events there are, the initial proof retrieval attempt of the universe proof courier can fail, causing it to go into a 30 second backoff. Because we used a hard coded timeout of 30 seconds for the transfer to complete, this sometimes failed the load test.
By making sure we use the same, configurable, timeout where relevant, we make the send process more reliable.
In addition, the following lines should be added to the load test nodes to shorten the duration of the backoff:
```
universerpccourier.initialbackoff=2s
universerpccourier.maxbackoff=30s
```

itest: use configurable timeout for load test

---

itest/integration_test.go
itest/test_harness.go
itest/universe_server_harness.go

In this commit we ensure that the universe server harness uses a new dedicated LND node. The universe harness previously used the Bob standby LND node. This change allows us to use an in-test tapd node with LND node Bob without conflicting with the universe server tapd node.
This change will be important when passing messages between tapd nodes (e.g. RFQ system) via LND nodes.
This work is necessary to complete: https://github.com/lightninglabs/taproot-assets/issues/766

itest: universe server harness uses a dedicated LND node

---

tools/check-go-version-dockerfile.sh
tools/check-go-version-yaml.sh

I noticed that the lint check (Go versions consistency check) was examining my local `vendor` directory. This directory contains project dependency files, which we shouldn't try to lint. Therefore this PR introduces an exclusion list to avoid checking certain directories.

tools: exclude non-project files from go version consistency lint check

---

itest/psbt_test.go
itest/test_list_on_test.go
tapcfg/server.go
tapfreighter/wallet.go
tapscript/interface.go
tapscript/send.go
tapscript/send_test.go
tx_validator.go
vm/testdata/vm_validation_generated.json
vm/testdata/vm_validation_generated_error_cases.json
vm/vm.go
vm/vm_test.go

This PR replaces https://github.com/lightninglabs/taproot-assets/pull/759 , as it introduces simple sighash functionality (`SIGHASH_ALL` and `SIGHASH_NONE`) for vPSBTs without changing the way we create the virtual transactions that are being signed. This allows us to be backwards compatible and does not require a new script version.

vPSBT: add sighash support (no version bump)

---

Makefile
itest/assertions.go
itest/multi_asset_group_test.go
proof/mock.go
rpcserver.go
tapdb/asset_minting.go
tapdb/asset_minting_test.go
tapdb/multiverse.go
tapdb/sqlutils.go
tapgarden/custodian.go
tapgarden/planter_test.go

Fix unit and integration test flakes

---

Makefile

Two improvements:
1. Passing tags to the makefile using the `tags` variable results in the tags being added twice. This PR removes that redundancy.
2. Preventing `git describe` to fail if it can't find a tag to describe the commit.

Makefile optimizations

---

Makefile

This commit addresses a specific issue encountered when executing the `build-itest` command in environments where a project's `vendor` directory exists. Previously, the command failed because the application `github.com/lightningnetwork/lnd/cmd/lnd` was not located within the `vendor` directory, leading to an unsuccessful build process.
The fix implemented involves modifying the Go build command to include the `-mod=mod` flag. This adjustment ensures that the build process automatically downloads any missing modules, circumventing the need for the application to be physically present in the `vendor` directory. It is important to note that directly including `lnd/cmd` or `lnd/cmd/lnd` within the `vendor` directory is not feasible, as the former is not a package, and the latter is an …

makefile: fix `build-itest` command failure when `vendor` dir present

---

itest/addrs_test.go
itest/psbt_test.go
itest/test_list_on_test.go

Based on #787 , #779 
Closes #577 
This PR introduces a basic itest that follows the flow of a trustless swap that is possible by correctly manipulating the sighash flags on the asset and bitcoin levels. We create an asymmetry between the vPSBT that describes the asset transfer and the PSBT that anchors it in a bitcoin transaction. The vPSBT only commits to the inputs, allowing anyone to define their own output, while the PSBT commits to the output (which asks for more bitcoin than what is provided in the anchor input) and allows someone to bring their own input to fulfill the transaction.
This way, the only way to "claim" the loose assets on the vPSBT layer is by bringing your own bitcoin on the PSBT layer, which would effectively be the pay-out for the asset holder who created this swap …

itest: trustless swap based on vPSBT/PSBT sighash flags

---

cmd/tapcli/universe.go

Related to https://github.com/lightninglabs/taproot-assets/issues/841.
In order to be able to directly import a proof leaf that was previously exported with `tapcli universe leaves` directly into the universe, we allow the proof to either be a proof file or a single transition proof.

cmd/tapcli: allow proof file or single proof on insert

---

tapgarden/custodian.go

Otherwise, as `lookupProofFilePath` will return an error if the file isn't found (which wraps `proof.ErrProofNotFound`), then the custodian will potentially fail to start up.

tapgarden: check for ErrProofNotFound when checking for local proof file

---

itest/rfq_test.go
rfqmsg/buy_accept.go
rfqmsg/buy_accept_test.go
taprpc/rfqrpc/rfq.pb.go
taprpc/rfqrpc/rfq.proto
taprpc/rfqrpc/rfq.swagger.json

This PR was recently reviewed, approved, and merged: https://github.com/lightninglabs/taproot-assets/pull/835
I noticed that some of the review comments could also apply to other parts of the RFQ code that were not changed in the above PR.
This PR improves the RFQ code following the review comments from https://github.com/lightninglabs/taproot-assets/pull/835.

RFQ cleanup

---

.github/workflows/main.yaml
.golangci.yml

The lll linter forces the code to be formatted with a maximum line length of 80 and a tab width of 8.
The `deadline` configuration is replaced with `timeout`. `deadline` is deprecated since v1.20 and will be removed in v1.57.0.
All line lengths in the repo are fixed where necessary, or ignored by adding a `nolint:lll` directive.

Add lll linter to golangci-lint configuration

---

itest/loadtest/mint_batch_test.go
itest/utils.go

When building images off the _**main**_ branch, I found that the load test pod was incapable of correctly determining the _**bitcoind**_ backend version:
```
➜  ✗ kubectl logs -f tapd-loadtest-orchestrator-job-11-zm76d
=== RUN   TestPerformance
=== RUN   TestPerformance/mint
=== NAME  TestPerformance
utils.go:149:
Error Trace:	/app/itest/utils.go:149
/app/itest/loadtest/utils.go:121
/app/itest/loadtest/mint_batch_test.go:28
/app/itest/loadtest/load_test.go:57
Error:      	unknown chain backend: %v
Test:       	TestPerformance
Messages:   	bitcoind v25.0.0 and above
=== NAME  TestPerformance/mint
testing.go:1490: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestPerformance (0.18s)
--- FAIL: TestPerformance/mint (0.18s)
FAIL
``` …

itest: small fixes for tapd load test

---

asset/asset.go
asset/asset_test.go
asset/mock.go
commitment/commitment_test.go
fn/iter.go
go.mod
internal/test/helpers.go
tapcfg/config.go
tapcfg/server.go
tapdb/asset_minting.go
tapdb/asset_minting_test.go
tapdb/assets_common.go
tapdb/assets_store_test.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/migrations/000017_seedling_script_group_keys.down.sql
tapdb/sqlc/migrations/000017_seedling_script_group_keys.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/assets.sql
tapgarden/batch.go
tapgarden/caretaker.go
tapgarden/interface.go
tapgarden/mock.go
tapgarden/planter.go
tapgarden/planter_test.go
tapgarden/seedling.go

Closes #820
Update the minting state machines to move batch funding into a separate command that can execute before batch finalization. Add a new command to supply group anchor witnesses before batch finalization.
Remaining TODOs:

tapgarden: add FundBatch and SealBatch requests

---

rfqmsg/buy_accept.go
rfqmsg/buy_accept_test.go
rfqmsg/buy_request.go
rfqmsg/buy_request_test.go
rfqmsg/messages.go
rfqmsg/reject.go
rfqmsg/reject_test.go
rfqmsg/sell_accept.go
rfqmsg/sell_accept_test.go
rfqmsg/sell_request.go
rfqmsg/sell_request_test.go

Closes https://github.com/lightninglabs/taproot-assets/issues/908

Add version fields to RFQ wire messages

---

rfq/manager.go
tapchannel/aux_invoice_manager.go

To allow direct peer (zero-hop) payments, we also need to be able to look up quotes we've accepted that our peer requested. The example flow here is: Dave creates an invoice (either specifying a BTC amount or asset amount, in any case the invoice is always denominated in milli-satoshi), Charlie has a direct channel with Dave and wants to pay the invoice with assets. Charlie only sees the milli-satoshi amount of the invoice and needs to find out how many asset units to send. For that, Charlie asks Dave for a quote over the given amount of milli-satoshi, gets an asset unit amount back. Charlie then creates an HTLC referencing that asset sell quote RFQ ID. But the invoice interceptor on Dave's side would previously not recognize that RFQ ID, because it's not an ID for a quote Dave requested …

rfq+tapchannel: track locally accepted quotes in manager

---

rfq/manager.go
rfq/negotiator.go
rfq/order.go
rfq/stream.go
rfqmsg/buy_accept.go
rfqmsg/sell_accept.go
tapchannel/aux_traffic_shaper.go

In this PR, we enrich incoming accept messages with corresponding sent requests. This involves storing outbound requests before sending and matching incoming accept message responses based on the RFQ quote `ID`. This matching process is performed in the RFQ stream service, ensuring that other RFQ services only encounter accept messages with fully populated fields, including the new request field.
As a result, transporting the asset ID in the accept message is no longer necessary. The asset ID can be found in the request message.
Removing the asset ID field from the accept wire message is important because it is redundant and isn't clear whether it is `out_asset` or `in_asset`. It also does not have a asset group key counterpart.

RFQ enrich incoming accept messages with sent requests

---

config.go
rfq/order.go
rfqmsg/accept.go
tapchannel/aux_closer.go
tapchannelmsg/custom_channel_data.go

Fixes the following issues:
- A panic during co-op close when one side didn't have any balance at all
- Format custom channel data to JSON in `PendingChannels` RPC
- Fix HTLC being rejected due to asset precision rounding issue
- Allow forwarding an asset-to-asset HTLC (single hop payment with asset channels on both sides)

Custom channel bug fixes

---

tapdb/multiverse.go
tapdb/schemas.go
tapdb/universe_stats.go

We have a bit over 130k assets on mainnet now, so 80k isn't large enough
to cache the entire response assuming no pagination.
We also start to log cache insertion failures.

tapd: temporarily increase query stats cache from 80k to 200k

---

itest/assets_test.go
itest/test_list_on_test.go
rpcserver.go
tapdb/asset_minting.go
tapgarden/caretaker.go
tapgarden/interface.go
tapgarden/planter.go

Should fix https://github.com/lightninglabs/taproot-assets/issues/940.
Likely caused by changes in https://github.com/lightninglabs/taproot-assets/pull/866.

tapgarden: batch restart fixes

---

tapchannelmsg/custom_channel_data.go

Testing indicated that when using large but valid asset amounts the channel custom records buffer size was greater than `tlv.MaxRecordSize`.
This commit introduces a new greater constant which will be used as the channel data max record size.
Addresses bug reported here: https://github.com/lightninglabs/taproot-assets/issues/942#issuecomment-2174129269
What is the correct value for this new constant?
NOTE: I haven't finished investigating why the record takes up more memory.

tapchannelmsg: increase channel data reader max record size

---

go.mod
go.sum
log.go
server.go
tapchannel/aux_leaf_creator.go
tapchannel/aux_leaf_signer.go
tapchannel/aux_traffic_shaper.go
tapchannel/commitment.go

Dependant on https://github.com/lightningnetwork/lnd/pull/8852
Requires LND version bump once the above PR is merged. Will remove from draft when ready for merge.
This PR is ready for review now.
In this PR, the traffic shaper's `PaymentBandwidth` method is modified to return the link bandwidth if the tap channel commitment blob or HTLC record is absent.
This modification ensures the traffic shaper returns the correct bandwidth for tap channels used as standard BTC lightning channels, ignoring any committed taproot assets.

server+tapchannel: modify PaymentBandwidth to return link bandwidth

---

itest/addrs_test.go
itest/assertions.go
tapdb/asset_minting.go
tapdb/assets_store.go
tapdb/interfaces.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/assets.sql
tapdb/sqlerrors.go

Fixes #951.
An (intermitent) failure popped up when running itest on the postgres backend.
This draft PR tries to solve this error, initially by unifying the behavior of both backends.
Currenlty the status is that this leads to an error later in the process (only for postgres), where the given number of events rhat exist with the given status is of by one.

Fix proof storage clobber error for postgres backend

---

go.mod
go.sum
server.go
tapchannel/aux_sweeper.go
tapfreighter/chain_porter.go

In this commit, we fix a bug in breach handling by ensuring we use the proper CSV delay when making the local commitment script key. Without this, we won't recognize an output as ours, and will fail to insert the justice transaction into the database.

tapchannel: update lnd dep and fix bug in breach handling 

---

tapchannel/aux_funding_controller.go

This ensures that the CLI won't hang indefinitely if the other party fails to respond for we/ reason (disconnected TCP connection, etc).

tapchannel: add 30 second timeout for funding ack

---

go.mod
go.sum
psbt_channel_funder.go

With this change, we'll use explicit negotiation for the new asset chan
specific chan type.

tapchannel: use taproot overlay chan type for asset chans

---

cmd/tapcli/assets.go
itest/assertions.go
itest/asset_meta_test.go
itest/utils.go
rpcserver.go

Resolves #972 by setting the dec display as the only JSON object when the given metadata is empty. The RPC request that causes this behavior is tested in the meta itest, and I manually tested the CLI for:
- Non-zero dec display, empty metadata, JSON meta type -> correct `taprpc.AssetMeta` struct is passed to the RPC, asset listed correctly after minting (this was with the exact CLI cmd Leo posted).
- zero dec display, empty metadata, JSON meta type -> rejected for empty metadata
- unknown meta type, empty metadata -> rejected for empty metadata (IIUC this was the existing behavior)

taprpc: Set dec display when metadata is empty

---

.github/workflows/release.yaml

Fixes the release build, see failed run here: https://github.com/lightninglabs/taproot-assets/actions/runs/9698686675/job/26765815638

github: check out release tag before building

---

sample-tapd.conf
tapdb/migrations.go
tapdb/migrations_test.go
tapdb/sqlite.go

This commit adds functionality to back up any existing SQLite database file before attempting a database migration.
The process involves creating a backup file, migrating the database, and removing the backup if no changes occurred to the 
database file. This approach avoids unnecessary backups but results in a backup being created and deleted each time tapd starts.

tapdb: backup sqlite db before running database migration

---

itest/asset_meta_test.go
rpcserver.go

Follow-on to #979 .
For minting via RPC, there was a missing check to prevent the decimal display value from being dropped before reaching the minter.

taprpc: decimal display requires JSON meta

---

tapdb/assets_store.go
tapdb/assets_store_test.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/queries/assets.sql

Discovered while adding more assertions in the `litd` custom channel itests.
This commit fixes two things:
- Because we could have multiple assets with the same script key, but in different anchor transactions, we also need to include the anchor outpoint of the input we want to mark as spent. Otherwise a duplicate script key (e.g. a second TAP channel funding script key, which is identical for every channel as it's just OP_TRUE) couldn't be set as spent anymore.
- Remove the TODO and LIMIT 1 workaround, since we now have a proper unique index preventing duplicate script keys _WITHIN THE SAME ANCHOR OUTPUT_.

tapdb: add anchor point to SetSpent, remove LIMIT 1

---

go.mod
go.sum
tapcfg/server.go
tapchannel/aux_closer.go
tapchannel/aux_sweeper.go

Otherwise, the transfer insert for the responder may fail as they don't
have the funding output in their database, so shipping the transfer
fails as it can't find the proof.
Fixes https://github.com/lightninglabs/taproot-assets/issues/985.

tapchannel: import funding output proofs for responder during co-op close

---

tapdb/sqlc/migrations/000020_asset_unique_key.up.sql

This commit changes the migration 20 to only do updates and deletes if
there are duplicates in the asset table. This is to avoid the risk of
potentially impact incorrectly otherwise consistent data.

tapdb: Predicate asset-entries-DB update/deletion by duplicate table

---

itest/assets_test.go
itest/test_list_on_test.go
proof/archive.go
proof/courier_test.go
proof/mock.go
tapdb/addrs.go
tapdb/asset_minting.go
tapdb/assets_common.go
tapdb/assets_store.go
tapgarden/batch.go
tapgarden/caretaker.go
tapgarden/interface.go
tapgarden/planter.go
tapgarden/planter_test.go
tapgarden/seedling.go

Fixes #986 .
As detailed in #986, recent changes around how batches are created updated the way we store seedlings; specifically when we store script keys and group keys. Changes were made to how batches were displayed, and those changes broke the display of batches minted with tapd versions 0.3.3 or earlier.
Further investigation showed that the `ListBatches` RPC (and matching CLI command) displayed incorrect information once assets from a batch had been transferred.
To fix this, we can re-read the assets minted in a batch from their issuance proofs that we stored on disk when finalizing the batch.

tapgarden: list batches correctly after asset transfer

---

rpcserver.go

If an old asset didn't have this field, then we can just assume that the value is zero, rather than error out.
Fixes https://github.com/lightninglabs/taproot-assets/issues/1001

proof: relax parsing in `DecDisplayForAssetID`

---

config.go
fn/errors.go
itest/tapd_harness.go
rfq/cli.go
rfq/manager.go
rfq/oracle.go
sample-tapd.conf
server.go
tapcfg/config.go
tapcfg/server.go
tapchannel/aux_leaf_creator.go
tapchannel/aux_leaf_signer.go
tapchannel/aux_traffic_shaper.go

Fixes #1007.
Fixes #1006.
Fixes #1010.
Also adds a fix for the startup dependency issue between `lnd` and `tapd`: Apparently it's possible that `lnd` wants to force close channels before the RPC server is fully started. That then calls into the aux leaf creator which blocks until `tapd` thinks it's fully started (which in turn depends on a successful connection to `lnd`'s RPC).
By making the aux leaf creator fully stateless and allowing some methods of the aux leaf signer that are stateless to be called early, we should be able to fix this startup dependency issue.

Custom channel testing bugfixes

---

tapgarden/mock.go
tapgarden/planter.go
tapgarden/planter_test.go

Fixes #999 and #1023 
Failures to fund or seal a batch on restart will longer block planter (and daemon) startup. Non-finalized batches that could not be funded or frozen will be marked as cancelled. Failing to finalize a batch will no longer stop the daemon.
This should prevent restart loops if the backing wallet is not funded, or cannot fund a minting batch.

tapgarden: fix batch handling on restart

---

address/book.go
tapcfg/server.go
tapchannel/aux_funding_controller.go
tapchannel/aux_traffic_shaper.go
tapfreighter/wallet.go

With this commit, we partially address https://github.com/lightninglabs/taproot-assets/issues/1026 by ensuring that when we
receive an incoming funding request, then we've already verified the
genesis proofs of the incoming asset.
If we haven't verified the proofs yet, then we'll try to fetch from a
remote universe. Otherwise, this check will be a noop.

tapchannel: ensure genesis proofs for input assets already known

---

tapchannel/aux_funding_controller.go

Once we call `fundVirtualPacket`, we've locked inputs assuming it succeeds. If for w/e reason, the remote peer fails to send us the first ack (before the call to `completeChannelFunding`), then before this commit, we would fail to unlock the inputs. Only after the call to `completeChannelFunding` would we unlock the UTXOs.
In this commit, we use two new defers to ensure that we always unlock the UTXOs if the pre-setup fails, and also if `completeChannelFunding` fails.
Fixes https://github.com/lightninglabs/taproot-assets/issues/1019

tapchannel: use defer to ensure lease unlocked if funding failure

---

itest/psbt_test.go
tapfreighter/chain_porter.go
tapfreighter/parcel.go

This pull request includes two changes to the `ChainPorter` states to improve clarity and better reflect their functionality.
1. **Rename `SendStateLogCommit` to `SendStateStorePreBroadcast`:**
- The state `SendStateLogCommit` has been renamed to `SendStateStorePreBroadcast`.
- This change clarifies that the state's functionality is to store data before broadcasting.
2. **Rename `SendStateReceiverProofTransfer` to `SendStateTransferProofs`:**
- The state `SendStateReceiverProofTransfer` has been renamed to `SendStateTransferProofs`.
- This change indicates that in this state, the `ChainPorter` may transfer multiple proofs, improving understanding of its purpose.
These changes enhance code readability and maintainability by providing more descriptive state names.

Improve Clarity in ChainPorter State Names

---

address/address.go
asset/asset.go
commitment/asset.go
rpcserver.go
tapdb/assets_store.go
tapdb/assets_store_test.go
tapfreighter/coin_select.go
tapfreighter/interface.go
tapfreighter/wallet.go
tapsend/send.go
tapsend/send_test.go

Closes https://github.com/lightninglabs/taproot-assets/issues/834
This PR introduces a new type named `AssetSpecifier` within the `asset` package. The `AssetSpecifier` type is designed to facilitate the conveyance of either an asset ID, an asset group public key, or both, throughout our codebase.
To demonstrate the utility of `AssetSpecifier`, this PR incorporates it in two key areas: coin selection and the derivation of tap commitment keys. While there are numerous potential applications for this new type across our project, this PR deliberately focuses on a select few to maintain brevity. The integration of `AssetSpecifier` sets the stage for future code contributions to leverage this type.

Add asset specifier

---

tapgarden/mock.go
tapgarden/planter_test.go

Addresses #974 .
The failure observed in CI was an empty confirmation event reached the caretaker in the test `basic_asset_creation`. That test case doesn't try to cause any faults in any mock interface, but `finalize_batch` does request that failure here:
https://github.com/lightninglabs/taproot-assets/blob/395a1806ab08d1ac49555dc5823598f070247895/tapgarden/planter_test.go#L1484
I concluded that the way we had implemented this fault injection was racy, so here we use atomic `Bool`s for tracking that state, that get unset after use.
I cannot reproduce the original failures locally after 100 runs of the `unit-race pkg=tapgarden` target.

tapgarden: improve fault injection in unit tests

---

cmd/tapcli/assets.go
tapchannel/aux_funding_controller.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1038.
Adds the missing `--show_leased` flag to the `tapcli assets list` subcommand.

tapcli: add --show_leased flag to assets list subcommand

---

Makefile
make/testing_flags.mk

This PR changes the behavior of the target `flake-unit-race` in the Makefile, to allow to run it for a specific package continuously.
Usage example: 'make flake-unit-race pkg=tapgarden'

Pass 'pkg' argument to `flake-unit-race` Makefile target

---

Makefile
scripts/release.sh

Closes https://github.com/lightninglabs/taproot-assets/issues/1045
To ensure our release binaries are reproducible, they must be built with a specific version of Go. This commit sets the `GOTOOLCHAIN` environment variable when building release binaries, ensuring that the build command uses the targeted Go version.
The `GOTOOLCHAIN` environment variable is supported only in Go version 1.21 or newer. This commit verifies that the invoked Go version meets this requirement.

makefile+scripts: specify Go version for building release binaries

---

tapdb/assets_store.go
tapdb/assets_store_test.go
tapdb/migrations.go
tapdb/sqlc/migrations/000022_transfer_outputs_proof_delivered.down.sql
tapdb/sqlc/migrations/000022_transfer_outputs_proof_delivered.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/transfers.sql
tapdb/sqlc/transfers.sql.go
tapfreighter/chain_porter.go
tapfreighter/interface.go
tapfreighter/parcel.go

This PR is work towards fixing https://github.com/lightninglabs/taproot-assets/issues/1009 (making the proof transfer process more robust).
This pull request adds a new `proof_deliver_complete` column to the `asset_transfer_outputs` table. It includes updates to the table schema, modifications to SQL statements, and adjustments to unit tests. Additionally, it integrates changes to the `tapfreighter` component for logging proof delivery confirmations.
1. **Schema Update**:
- Added the `proof_deliver_complete` column to the `asset_transfer_outputs` table.
2. **SQL Statement Modifications**:
- Updated the row insertion and retrieval SQL statements to include the `proof_deliver_complete` column.
- Added a new SQL statement specifically for modifying the `proof_deliver_complete` column.
3. …

Store transfer output proof delivery status

---

feature_bit_verifier.go
go.mod
go.sum
tapcfg/server.go
tapchannel/aux_funding_controller.go

With the way the protocol works as is, we signal the optional feature bit, so connections can be made with older peers. Rather than timeout after they don't recognize our custom message, we'll instead use the feature bits to detect early if they don't understand the new protocol.
Fixes https://github.com/lightninglabs/taproot-assets/issues/1038

tapchannel: check for feature bits before opening chans

---

tapchannel/aux_funding_controller.go

If the funding attempt takes a while and/or the users cancels the original request, if we're using the context passed along, then we may fail to actually unlock all the inputs:
```
2024-08-03 13:13:54.004 [ERR] TCHN: unable to unlock inputs: unable to unlock outpoint X:2: error listing existing leases: rpc error: code = Canceled desc = context canceled
2024-08-03 13:13:54.004 [DBG] TCHN: unlocking asset inputs: ([]wire.OutPoint) (len=1 cap=1) {
(wire.OutPoint) X:1
}
2024-08-03 13:13:54.004 [ERR] TCHN: Unable to unlock asset inputs: unable to unlock asset outpoints [X:1]: unable to release coins: context canceled
```
This commit fixes that by using a fresh context.

tapchannel: use new context for call to unlockLeases

---

fn/option.go
itest/psbt_test.go
itest/send_test.go
itest/test_list_on_test.go
tapdb/assets_store.go
tapdb/multiverse.go
tapfreighter/chain_porter.go
tapfreighter/interface.go
tapfreighter/parcel.go
tapgarden/custodian.go

Some of the commits in this PR refactor the code for clarity and don't modify functionality.
The overall goal of this PR is to ensure that we don't try to deliver proofs which have already been delivered. And that we reattempt proof delivery on node restart.
Related to https://github.com/lightninglabs/taproot-assets/issues/1009

Reattempt proof delivery on node restart

---

.github/workflows/main.yaml
make/testing_flags.mk

Second attempt to update CI so that coverage info for unit tests is uploaded to Coveralls (and could be displayed for future PRs).
I looked at the setup for btcd:
https://github.com/btcsuite/btcd/blob/master/.github/workflows/go.yml
https://github.com/btcsuite/btcd/blob/b161cd6a199b4e35acec66afc5aad221f05fe1e3/Makefile#L109
I think we don't need to change directory into subfolders for unit tests since we don't have sub-packages in this repo?
Itest coverage may more involved so deferring that for a separate PR.

CI: push coverage file for unit tests

---

rfq/oracle.go
rfq/oracle_test.go

Fixes the problem that because of the missing allocation, the subject asset ID was always set to an empty slice.
Reported by Luke in Slack, thanks a lot for pointing out the problem!

rfq: actually set subject asset in QueryRateTick

---

.github/workflows/main.yaml
Makefile
scripts/check-migration-numbering.sh
scripts/gen_sqlc_docker.sh
tapdb/migrations.go
tapdb/postgres.go
tapdb/sqlc/migrations/000002_assets.up.sql
tapdb/sqlc/migrations/000003_addrs.up.sql
tapdb/sqlc/migrations/000005_transfers.up.sql
tapdb/sqlc/migrations/000006_addr_event.up.sql
tapdb/sqlc/migrations/000007_universe.up.sql
tapdb/sqlc/migrations/000013_universe_fed_proof_sync_log.up.sql
tapdb/sqlc/migrations/000014_multiverse_tree.up.sql
tapdb/sqlc/migrations/000016_tapscript_trees.up.sql
tapdb/sqlc/migrations/000023_multiverse_tree_re_apply.down.sql
tapdb/sqlc/migrations/000023_multiverse_tree_re_apply.up.sql
tapdb/sqlite.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1071.
This PR is the result after almost two days of debugging #1071.
The TL;DR is: due to a git branch cherry-pick mishap, the migration number 14 wasn't included in the `v0.3.3` release version. Some users then applied the migration directly as it was in the source directory, which lead to them not having properly working auto incrementing primary keys.
The first commit in this PR adds a CI check that verifies migration numbers in the file names are continuous.
The second commit re-applies the migration 14 (somewhat modified) as migration 23.
The last commit then fixes the workaround with the primary key type replacements we used. See comment in `scripts/gen_sqlc_docker.sh` if you want to understand the full problem and …

tapdb: fix multiple issues around migration file handling

---

proof/courier.go
proof/courier_test.go
proof/mock.go
tapchannel/aux_sweeper.go
tapfreighter/chain_porter.go
tapgarden/custodian.go
tapgarden/custodian_test.go

Related to https://github.com/lightninglabs/taproot-assets/issues/1082
This commit enables establishing a connection to a proof courier service without specifying a particular recipient (proof owner). This change allows us to:
* Share proof courier service connections among multiple recipient peers.
* Test connections to the proof courier service earlier in the process, before the proof owner recipient is specified. This test can now occur before the anchor transaction broadcast in the ChainPorter's state machine.

multi: specify proof courier proof recipient at delivery or receive

---

proof/courier.go
proof/courier_test.go
proof/mock.go
proof/verifier.go
tapchannel/aux_sweeper.go
tapfreighter/chain_porter.go
tapgarden/custodian.go

This PR introduces updates to the HashMail and UniverseRPC proof courier handlers, specifically making connection attempts optionally lazy. The changes are aimed at enhancing the robustness of the connection handling process by integrating these attempts into the backoff procedure where feasible.

Enhance Proof Courier Handlers with Lazy Connection Attempts for HashMail and UniverseRPC

---

universe/base.go
universe/syncer.go

I encountered this on `testnet` while trying to reproduce https://github.com/lightninglabs/taproot-assets/issues/675.
Can be reproduced with:
```
--universe.sync-all-assets
--universe.federationserver=testnet.universe.lightning.finance:10029
```
And `tapcli u s --universe_host testnet.universe.lightning.finance:10029`.
This PR fixes the issue by making sure any group anchors are inserted into the DB first.

[universe]: fix proof sync for large asset minting batches

---

asset/asset.go
asset/asset_test.go
commitment/commitment_test.go
commitment/split.go
proof/courier.go
proof/verifier.go
tapfreighter/wallet.go

In this commit, we fix an existing bug related to lock times and split commitments. Before this commit, if an input had a relative lock time, then when we went to make the new split assets, we would _copy_ that value into the split. This isn't correct as the input is valid/confirmed, so we don't need to copy over the lock time information.
The prior behavior would cause certain classes of spends to fail, as we would be validating a new root asset that has no lock time, but the root asset split inserted into the split commitment would be carrying the old lock time. When verifying the split, we would set the lock times of the split to that of the new asset:
https://github.com/lightninglabs/taproot-assets/blob/e893dee87e9d8f0de53b8ee9e2527add80df6491/vm/vm.go#L305-L307.
As we copied over the …

commitment: splits shouldn't inherit locktime from inputs

---

server.go

I noticed that user log files were unnecessarily verbose, therefore, this PR downgrades some log messages from info to trace.

Server logging cleanup

---

fn/concurrency.go
fn/func.go
tapfreighter/chain_porter.go

This PR updates the proof delivery process in `ChainPorter` by utilizing the newly introduced `ParSliceErrCollect` function. This change ensures that proof delivery continues even if an individual transfer output proof encounters an error, improving the reliability of the delivery process.
This change ensures that as many transfer output proofs as possible are delivered, even in the presence of errors.
- **New Function**: Introduced `ParSliceErrCollect`, which collects errors during parallel processing without halting the entire operation.
- **ChainPorter**: Modified to use `ParSliceErrCollect` for parallel proof delivery, allowing the process to continue despite individual delivery failures.
Related to: https://github.com/lightninglabs/taproot-assets/issues/1082

Enhance Proof Delivery Resilience with ParSliceErrCollect in ChainPorter

---

.github/workflows/main.yaml

fixes: https://github.com/lightninglabs/lightning-terminal/issues/827

github: run LiT itests & unit tests as part of CI 

---

itest/loadtest/README.md
itest/loadtest/config.go
itest/loadtest/load_test.go
itest/loadtest/loadtest-sample.conf

This PR is based on https://github.com/lightninglabs/taproot-assets/pull/662 by @calvinrzachman. It is an update / revisited version for our loadtesting setup and metrics collection.

Loadtesting metrics, updated

---

.github/workflows/main.yaml
itest/loadtest/config.go
itest/loadtest/load_test.go

Fixes formatting of build tag excluded files the linter didn't pick up on.
And fixes the new itest to actually run against the correct `litd` branch (I missed that during review). At the same time we slightly optimize the litd itest build.

Small fixes after recent PRs

---

internal/test/helpers.go
tapchannel/auf_leaf_signer_test.go
tapchannel/aux_leaf_signer.go

Fixes #1114 .
This PR updates the aux signer to handle cancel and quit signals in a similar fashion to the 'primary' sig job handler in `lnwallet/sigpool`. This also improves safety as the cancel channel can now be closed by both `tapd` and `lnd`.

tapchannel: improve aux signer signal handling

---

fn/concurrency.go
proof/verifier.go

Noticed while reading #675 .
The impact of a mismatch between `runtime.NumCPU()` and `GOMAXPROCS` is a known issue:
https://github.com/golang/go/issues/33803
https://github.com/uber-go/automaxprocs
Tl;dr, if a user wants to limit the OS threads used by `tapd` and sets `GOMAXPROCS`, that will have no effect right now. Reading `GOMAXPROCS` is preferred to `runtime.NumCPU()` for setting the size of a CPU-bound worker pool. This matches `runtime.NumCPU()` by default.
https://pkg.go.dev/runtime#GOMAXPROCS

fn+proof: use GOMAXPROCS for worker pool size

---

tapdb/asset_minting.go

tapdb: improve batch marshalling

---

.github/workflows/main.yaml

Some lightning-terminal (LiT) itests are currently flaky. This commit restricts CI to running only the `custom_channels` subset of LiT itests.

ci: run only custom_channels LiT itests

---

go.mod
go.sum
server.go
tapchannel/aux_traffic_shaper.go
tapchannel/commitment.go

This PR adds some small fixes for liquidity related bugs that were reported on tap channels.

Tap channels liquidity fixes

---

rfqmath/fixed_point.go

This commit updates the documentation for `FixedPoint.Mul` and `FixedPoint.Div` to specify that these methods cannot be used with arguments having different scale values from the target fixed-point. This clarification helps prevent misuse of these methods.

rfqmath: clarify scale requirement in FixedPoint Mul and Div docs

---

rfq/negotiator.go
rfqmath/arithmetic.go
rfqmath/fixed_point.go
rfqmath/fixed_point_test.go

This pull request introduces the following changes to the `rfqmath` library:
1. **FixedPoint[T].WithinTolerance method**  
Adds the `WithinTolerance` method to the `FixedPoint[T]` type, allowing two fixed-point numbers to be checked for equality within a specified tolerance in Parts Per Million (PPM).
2. **Greater-than operators for integer types**  
Adds support for handling the `>` and `>=` comparisons for integer types.
These changes are necessary towards closing https://github.com/lightninglabs/taproot-assets/issues/871.

Add fixed-point `WithinTolerance` method and greater-than operators

---

rfqmsg/messages.go
rfqmsg/reject.go
rfqmsg/reject_test.go
taprpc/marshal.go

This PR aligns the RFQ reject wire message with the BLIP changes found here https://github.com/Roasbeef/blips/pull/4
This PR is related to https://github.com/lightninglabs/taproot-assets/issues/871
These changes require a quote reject wire message version bump. We need to ensure that all RFQ breaking changes go into the same release. I've decided to spin them into their own PR because the scope of change is very narrow, these commits are small.

Align RFQ reject message with BLIP

---

rpcperms/interceptor.go
server.go

This PR fixes some startup related bugs that were discovered when integrating tapd with litd.
Read more [here](https://github.com/lightninglabs/taproot-assets/issues/1122)
Closes https://github.com/lightninglabs/taproot-assets/issues/1122

Startup related fixes

---

tapchannel/auf_leaf_signer_test.go

Fixes #1143 . I had replicated the original failure locally, race tested this change for 100 iterations locally.

tapchannel: relax timing for quit and cancel tests

---

rfqmath/convert_test.go

Simplified example. Dealing with dollars and not cents.

rfqmath: simplify price oracle rate example

---

tapchannel/aux_closer.go
tapchannel/aux_funding_controller.go
tapchannel/aux_sweeper.go
tapdb/assets_store.go
tapdb/assets_store_test.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/queries/assets.sql
tapscript/script.go
tapscript/script_test.go

This commits modifies the SQL queries `QueryAssetBalancesByGroup` and
`QueryAssetBalancesByAsset` to allow an `exclude_key` parameter to
exclude assets with that key from the balance calculation.
`assetsStore.QueryBalancesByAsset` and
`assetsStore.QueryAssetBalancesByGroup` use this parameter to exclude
assets that are specifically used for funding custom channels. The
balance of these assets should be reported through the L2 channel
balance and not through the L1 asset balance.

tapd: fix L1 assets balance calculation

---

rfq/negotiator.go
rfq/oracle.go
rfq/oracle_test.go
rfqmsg/buy_accept.go
rfqmsg/buy_request.go
rfqmsg/messages.go
rfqmsg/request.go
rfqmsg/sell_accept.go
rfqmsg/sell_request.go
taprpc/priceoraclerpc/marshal.go

This PR refines the RFQ code to ensure that asset rate expiry timestamps are correctly passed to and retrieved from the price oracle service.
Previously, rate expiry timestamps were not consistently provided to the price oracle.
1. **New `AssetRate` Type**:  
Introduces the `AssetRate` type to represent an asset's exchange rate to BTC, along with its expiration timestamp.
```go
// AssetRate represents the exchange rate of an asset to BTC, encapsulating
// both the rate in fixed-point format and an expiration timestamp.
//
// Combining these fields ensures that each rate is inherently tied to an
// expiry, clarifying its validity period.
type AssetRate struct {
// Rate defines the exchange rate of asset units to BTC using a
// fixed-point representation, ensuring precision for fractional …
```

Ensure that asset rate hint expiry timestamps are passed to price oracle

---

chain_bridge.go
docs/examples/basic-price-oracle/go.mod
docs/examples/basic-price-oracle/go.sum
go.mod
go.sum
rpcserver.go
tapcfg/config.go
tapchannel/aux_funding_controller.go
tapgarden/interface.go
tapgarden/mock.go
wallet_anchor.go

This PR adds `MinRelayFee` to the `WalletAnchor` and uses it during tapchannel funding to check whether the feerate meets the minimum relay fee.
fixes: #1105
~~This PR depends on  https://github.com/lightninglabs/lndclient/pull/200 and uses a pseudoversion of that package.~~
~~go.mod should be changed before merging this PR,~~

min_relay_fee check during channel funding

---

scripts/gen_sqlc_docker.sh

In this commit, we fix an issue I observed on my machine after updating many command line/dev utilities.
I observed that if the script failed for w/e reason, then the old files weren't properly restored.
The repro on my machine is something like:
1. Shutdown docker, make sure the daemon isn't accessible.
2. Run `mac sqlc`. The script should fail.
3. Observe that the files in your local working tree are still altered.
We fix this by using the `trap` command, [which is basically like Go's `defer`, but for bash
scripts](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html)!

scripts: use `trap` to make sure old files always restored

---

proof/courier.go
sample-tapd.conf
tapcfg/config.go
tapdb/postgres.go

This fixes an issue where tapd would shut down because querying channels on a slow lnd would time out:
```
2024-10-30 10:06:21.535 [DBG] STAT: Setting the taproot-assets sub-server as errored: received critical error from sub-server (taproot-assets), shutting down: failed to handle outgoing message: error adding local alias: add alias: error listing local channels: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
Will add a similar PR to `litd`, as there the `lndclient` is created in a single place for all sub servers, so this daemon specific value would be ignored.

tapcfg: allow to configure lnd RPC timeout, increase default val

---

tapdb/addrs.go
tapdb/addrs_test.go
tapdb/asset_minting.go
tapdb/assets_common.go
tapdb/assets_store.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/queries/assets.sql
tapdb/sqlutils.go

In this commit, we fix some incorrect handling on null bool in SQL, that
looks to be mostly benign. Before this commit, instead of doing `.Bool`,
we did `.Valid`. The latter is only useful to check if something is
zero, or NULL. In this case, we can just go with the bool value
directly.
Then, we update `InsertScriptKey` to allow flipping known to
true, if it was false before.
This is useful as at times a script key from a smart contract might have
been inserting on disk, but with declared known as false. Then if we
tried to insert it again, with known as true, the upsert logic would end
up making no change on disk.
Note that without the initial bug fix, the test added in the last commit 
would fail.

tapdb: fix bug w.r.t null bool handling, allow InsertScriptKey to allow flipping known to true 

---

.github/workflows/main.yaml

This PR fixes a typo in the `go.mod` replace directive for the taproot-assets dependency

Fix LitD itest CI

---

sample-tapd.conf
tapcfg/config.go
tapcfg/server.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1024.
This commit adds a new universe.no-default-federation boolean flag that allows the user to disable adding the default federation server.

tapcfg: add flag to disable default federation server

---

rfq/order.go

Due to the integer nature of asset units, when converting to milli-satoshi and back, we might be off by a fraction of an asset unit when comparing to the milli-satoshi amount of an HTLC. We'll add a single asset unit to the reported inbound amount when checking in-out amount compliance to allow for those asset rounding imprecisions. In a real-world scenario where an asset has a decimal display value of 6, this would result in an imprecision of fractions of cents and be earned back by the spread on the actual conversion itself.

rfq: fix precision issue in HTLC compliance check

---

proof/proof_stitching_test.go

This helped me verify and fix proofs in https://github.com/lightninglabs/taproot-assets/issues/1168 and I think the code might be useful for other things too. It won't run in CI, so no harm in keeping it IMO.

proof: add code for stitching together failed proof suffixes

---

rfq/manager.go
rfq/negotiator.go
rfq/order.go
rfqmsg/accept.go
rfqmsg/buy_accept.go
rfqmsg/buy_request.go
rfqmsg/messages.go
rfqmsg/request.go
rfqmsg/sell_accept.go
rfqmsg/sell_request.go
rpcserver.go
tapchannel/aux_invoice_manager.go
tapchannel/aux_invoice_manager_test.go
tapchannel/aux_traffic_shaper.go
taprpc/marshal.go

Improve docs for: `SellOrder`, `SellRequest`, `BuyOrder`, `BuyRequest`.
Populate transfer type field in request.
Make use of `AssetRate` type.

More RFQ improvments

---

docs/examples/basic-price-oracle/go.mod
docs/examples/basic-price-oracle/go.sum
go.mod
go.sum
psbt_channel_funder.go
sample-tapd.conf
server.go
tapcfg/server.go
tapchannel/aux_funding_controller.go
tapchannel/aux_leaf_signer_test.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1149
Depends on https://github.com/lightninglabs/taproot-assets/pull/1130.
Addresses comment in https://github.com/lightningnetwork/lnd/pull/9072#discussion_r1765319065.

Limit number of HTLCs in custom channel

---

itest/assertions.go
itest/fee_estimation_test.go
itest/send_test.go
proof/proof_test.go
tapfreighter/chain_porter.go
tapfreighter/coin_select.go
tapfreighter/wallet.go
tappsbt/interface.go
tappsbt/interface_test.go
tapsend/send.go
tapsend/send_test.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1168 (or at least prevents it from happening in the future).
This PR enforces script keys to be unique per top-level MS-SMT tree (assetID/groupKey) within a single transfer.
To be able to test this properly, we also make sure selected UTXOs are released by the freighter if the shipment of a parcel results in an error.
That change then impacts some assumptions in the integration tests, which requires additional commits to fix.

[tapsend]: Enforce unique script keys

---

itest/addrs_test.go
itest/send_test.go
itest/test_list_on_test.go
itest/utils.go
rpcserver.go
tapfreighter/chain_porter.go
tapgarden/planter.go

Both the minting transaction and normal on chain transactions suffer from edge cases where the fee estimation comes up with a fee that doesn't meet the current min relay fee. This PR changes that behavior by checking the estimated fee against the min relay fee, and bumps the fee if it doesn't clear the minimum fee height implied by min relay fee.
fixes #1171

Fee bumping when fee estimation doesn't meet min relay fee

---

make/testing_flags.mk
tapdb/migrations.go
tapdb/sqlc/migrations/000024_universe_optimization_indexes_queries.down.sql
tapdb/sqlc/migrations/000024_universe_optimization_indexes_queries.up.sql
tapdb/sqlc/querier.go
tapdb/sqlc/queries/universe.sql
tapdb/sqlc/universe.sql.go
tapdb/universe_perf_long_test.go
tapdb/universe_perf_short_test.go
tapdb/universe_perf_test.go
tapdb/universe_stats.go

This PR introduces two key improvements:
1. Strategic composite indices to optimize `tapdb` universe queries
2. Enhanced lock safety for concurrent stats access
```go
// Added finer-grained locking for stats access
statsCacheLogger    *cacheLogger
statsRefresh        *time.Timer
eventsMtx          sync.RWMutex    // Upgraded from sync.Mutex
assetEventsCache   assetEventsCache
eventsCacheLogger  *cacheLogger
syncStatsMtx      sync.RWMutex    // Upgraded from sync.Mutex
syncStatsCache    *atomicSyncStatsCache
syncStatsRefresh  *time.Timer
```
Key changes:
- Upgraded mutexes to RWMutex for better concurrency
- Separated read/write lock paths in QueryAssetStatsPerDay and QuerySyncStats
- Proper lock ordering to prevent deadlocks
- Added atomic cache for sync stats
```sql
-- Optimizes universe …
```

tapdb: Add Universe indices, optimize SQL queries, `RWMutex` for cache

---

cmd/tapcli/assets.go
itest/burn_test.go
perms/perms.go
rpcserver.go
tapdb/assets_store.go
tapdb/assets_store_test.go
tapdb/migrations.go
tapdb/sqlc/migrations/000025_burns.down.sql
tapdb/sqlc/migrations/000025_burns.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/transfers.sql
tapdb/sqlc/transfers.sql.go
tapfreighter/chain_porter.go
tapfreighter/interface.go
tapfreighter/parcel.go
taprpc/taprootassets.pb.go
taprpc/taprootassets.pb.gw.go
taprpc/taprootassets.pb.json.go
taprpc/taprootassets.proto
taprpc/taprootassets.swagger.json
taprpc/taprootassets.yaml
taprpc/taprootassets_grpc.pb.go

We're currently able to provably burn assets with tapd but we have no (easy) way of retrieving burn related historical data. This PR adds a DB table and exposes some new RPC methods/parameters to help keep track of burns.
When completing an asset burn, we add an entry to the new burns table. We also add a new `ListBurns` method which returns a list of all burns that pass the user-provided filters (asset id, group id, anchor txid)
Closes #1095

Add `ListBurns` RPC 

---

docs/examples/basic-price-oracle/go.mod
docs/examples/basic-price-oracle/go.sum
go.mod
go.sum
itest/send_test.go
itest/tapd_harness.go
itest/test_list_on_test.go
virtual_tx_signer.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1208.
Depends on https://github.com/lightninglabs/lndclient/pull/203.
Fixes an issue with how we tell `lnd` what key to sign. This basically boils down to a weird behavior in `lndclient` that we now circumvent with a new signing method.

[wallet]: fix signing interaction with lnd, allowing restore from seed

---

taprpc/tapchannelrpc/tapchannel.pb.gw.go
taprpc/tapchannelrpc/tapchannel.swagger.json
taprpc/tapchannelrpc/tapchannel.yaml

Closes https://github.com/lightninglabs/taproot-assets/issues/1219

tchrpc: change FundChannel endpoint to POST

---

tapchannel/allocation_sort.go
tapchannel/allocation_sort_test.go
tapchannel/aux_leaf_creator.go
tapchannel/aux_leaf_signer.go
tapchannel/aux_leaf_signer_test.go
tapchannel/aux_sweeper.go
tapchannel/commitment.go
tapchannel/log.go
tapdb/addrs_test.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/queries/assets.sql
tapsend/send.go

Fixes the LiT integration tests that were broken after merging https://github.com/lightninglabs/taproot-assets/pull/1181.
But that basically showed us that colliding script keys for MPP shard HTLCs are actually a problem.
This PR tweaks each script key with the HTLC index, making them unique again, even if they have the same payment hash and timeout (which results in the same BTC level taproot output key).
To make the accompanying [`litd` integration tests](https://github.com/lightninglabs/lightning-terminal/pull/908) pass, we also fix the following two bugs:
- Calculate the sweep transaction change output index correctly and dynamically to avoid invalid exclusion proofs when there are multiple HTLCs being swept at the same time.
- Fix an issue with `UpsertScriptKey` that wouldn't allow …

[custom channels]: generate unique script keys for HTLCs

---

version.go

Prepare for tagging a first RC of `v0.5.0-alpha`.
To be merged **AFTER** https://github.com/lightninglabs/taproot-assets/pull/1209.
Requesting review from the whole team to share the joy of achieving this milestone.

version: bump to version v0.5.0-alpha.rc1

---

cmd/tapcli/universe.go
itest/assertions.go
sample-tapd.conf
tapdb/multiverse.go
tapdb/multiverse_cache.go
tapdb/universe.go
universe/interface.go
universe/syncer.go

This fixes an issue with a new tapd (v0.5.0-rc1) attempting to sync with an old (v0.4.1) universe server. Because we now serve all the root nodes from a cache, we allow a much larger page size when requesting the root nodes. But old universe servers will not yet allow that higher request limit, resulting in the following error:
[/universerpc.Universe/AssetLeafKeys]: invalid request limit
So we need to use the old limit when _requesting_ pages. And once most of the universe servers have been updated (e.g. v0.5.1), we can then also use the larger limit on requests.

multi: roll back change in request page size

---

rfq/negotiator.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1227.
Because we don't return if the error returned from the price oracle is non-nil, the asset rate might be nil in case we couldn't talk to the oracle. So we need to use fn.MaybeSome() instead of fn.Some() with a dereference.

rfq: fix potential nil pointer panic

---

rpcserver.go

A user observed that when using Python, they get an EOF even if the payment succeeds. My guess is that `lnd` has hung up, then we try to recv and get an EOF error. With this PR, we try to catch that EOF error and just return `nil`. 
One other idea: do we need to call `CloseSend` at the very end or in a defer?
Fixes: https://github.com/lightninglabs/taproot-assets/issues/1216

rpc: try to catch EOF error from lnd sendpayment

---

asset/asset.go
asset/asset_test.go
asset/mock.go
itest/assertions.go
proof/encoding.go
proof/mint.go
proof/mock.go
proof/proof.go
proof/proof_test.go
proof/records.go
rpcserver.go
tapdb/universe.go
tapdb/universe_test.go
tapgarden/caretaker.go

Rename the existing `GroupKeyReveal` struct to `GroupKeyRevealV0` and introduce a new `GroupKeyReveal` interface. This change enables adding new versions of `GroupKeyReveal` while retaining the V0 type for proper documentation of its behavior.
Support for `GroupKeyReveal` V0 will be preserved.

Refactor GroupKeyReveal for multi-version support

---

chain_bridge.go
rfq/manager.go
rfq/order.go
tapcfg/server.go

This PR adds a simple in-memory tracking of accepted htlcs in the RFQ policy level. HTLCs that passed the policy check are now tracked by each policy, possibly affecting future policy check outcomes (depends on individual policy's implementation)

Track HTLCs in rfq policies

---

address/address.go
address/address_test.go
address/book.go
asset/witness.go
asset/witness_test.go
proof/meta.go
proof/verifier.go
rfqmsg/custom_channel_data.go
rpcserver.go
tapchannel/aux_funding_controller.go
tapchannelmsg/custom_channel_data.go
tapchannelmsg/records.go
tapchannelmsg/records_test.go
tapdb/addrs.go
tapdb/assets_store.go
tapfreighter/parcel.go
taprpc/marshal.go
tapsend/send.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1067.
Adds the decimal display value to the channel funding blob, so it can be rendered for `lncli listchannels` and `lncli pendingchannels`.
To make the code in the funding manager as nice as possible, we first do some refactor.

[custom channels]: add decimal display to channel funding blob

---

docs/examples/basic-price-oracle/go.mod
docs/examples/basic-price-oracle/go.sum
go.mod
go.sum
rpcserver.go
server.go
tapchannel/aux_traffic_shaper.go
tapchannel/commitment.go
taprpc/marshal.go

Depends on https://github.com/lightningnetwork/lnd/pull/9333.
Fixes the issue that would lead to a force close if the channel bandwidth of a target channel during a forward event isn't sufficient.
Also fixes https://github.com/lightninglabs/taproot-assets/issues/1234 (drive-by fix) and another edge case found during integration tests.

[custom channels]: Fix bandwidth manager and other bugs

---

.github/workflows/release.yaml

The release notes template has been updated to improve the paragraph on
timestamps. It now correctly specifies both ots artifacts and how to use
them to verify the timestamps of the manifest and its signature.
Secondly, the template now explains how the timestamp of the _git tag_
can be verified by using the OpenTimestamps git wrapper.

Update release notes template re timestamps

---

asset/asset.go

Changes the behavior of the group key reveal v1.

asset: change all-zero hash to empty leaf

---

fn/option.go
rfq/negotiator.go
server.go
tapchannel/aux_funding_controller.go
universe/auto_syncer.go

Refine selected log messages to enhance clarity and reduce clutter in log files.
Also add log messages for price oracle query.

Improve logging

---

itest/loadtest/load_test.go

Using [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: using slices.Contains to simplify the code

---

.github/workflows/main.yaml

tapd's CI tests using litd tests has failed to run.  CI failed to run due to the `LITD_ITEST_BRANCH:` CI environment variable not being updated after the merge of litd's `update-to-lnd-18-4` branch.
This CI gap was observed during review of another review:
https://github.com/lightninglabs/taproot-assets/actions/runs/12690734269/job/35454398525?pr=1283#step:4:63
<details>
<summary>CI details</summary>
<br>
Run actions/checkout@v3
Syncing repository: lightninglabs/lightning-terminal
Getting Git version info
Temporarily overriding HOME='/home/runner/work/_temp/54a16043-e669-4360-a3d6-f41d903bdcc8' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory …

GitHub: update tapd's CI litd branch to testing target

---

universe/auto_syncer.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1293.
When syncing a single asset (for example for creating an address) fails, the cause isn't easily visible in the logs. First, because the actual remote error wasn't logged and second because it was logged as debug. This commit fixes both.

universe: improve logging for single asset sync attempt

---

asset/asset_test.go

This PR introduces a comprehensive unit test for the `PubKey` method of the `ExternalKey` struct. The test covers various scenarios, including valid and invalid derivation paths, ensuring the method's correctness and error handling.
---
This PR depends on https://github.com/lightninglabs/taproot-assets/pull/1272 . This PR should be merged after https://github.com/lightninglabs/taproot-assets/pull/1272 has been merged. I will keep in draft until https://github.com/lightninglabs/taproot-assets/pull/1272 is merged.

Add unit test for method ExternalKey.PubKey

---

.github/workflows/main.yaml

Bumps the github workflow action `upload-artifact` from v3 to v4
([Migration Doc](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md))

github-ci: bump upload-artifact@v3 to @v4

---

itest/assertions.go

I observed flakiness in the CI PostgreSQL integration tests. Here's an example of a failure: https://github.com/lightninglabs/taproot-assets/actions/runs/12827900128/attempts/1?pr=1307
The issue occurred around commit ffef906c.
This might be happening because proofs are being transferred manually before the tapd state machine has a chance to process them. Alternatively, it could be due to tapd returning an error in the event stream with an out-of-order send state, realizing it cannot transfer the proofs that haven't yet been manually transferred.
To address this, I've added additional logging to help diagnose the issue if the flakiness occurs again.
```
2025-01-17T11:23:01.4314022Z     assertions.go:1023: 
2025-01-17T11:23:01.4314648Z         	Error Trace: …
```

Add Logging to Diagnose Flaky CI PostgreSQL Integration Test

---

asset/asset.go
docs/examples/basic-price-oracle/go.mod
docs/examples/basic-price-oracle/go.sum
docs/external-group-key-ledger.md
go.mod
go.sum
tapgarden/planter.go

~Depends on https://github.com/lightninglabs/taproot-assets/pull/1290.~
Depends on https://github.com/lightninglabs/taproot-assets/pull/1295.
Adds the necessary meta information to the group key VM transaction PSBT to allow signing of such a mint authorization transaction using a [custom version of the HWI library](https://github.com/lightninglabs/HWI/tree/tapd-cold-minting) and a Ledger signing device.
A new guide documents the required steps.

Support minting on Ledger signing device

---

sqlc.yaml
tapdb/migrations.go
tapdb/sqlc/addrs.sql.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/macaroons.sql.go
tapdb/sqlc/metadata.sql.go
tapdb/sqlc/migrations/000027_better_universe_stats.down.sql
tapdb/sqlc/migrations/000027_better_universe_stats.up.sql
tapdb/sqlc/mssmt.sql.go
tapdb/sqlc/transfers.sql.go
tapdb/sqlc/universe.sql.go
tapdb/universe_perf_long_test.go
tapdb/universe_perf_short_test.go
tapdb/universe_perf_test.go
tapdb/universe_stats_test.go

Addition to https://github.com/lightninglabs/taproot-assets/pull/1302.
Difference can best be seen when running `make unit-trace pkg=tapdb long-tests=1 case=TestUniverseIndexPerformance/name=query_aggregated`:
```
universe_perf_test.go:279: No indices exec time: 28.961577804s
universe_perf_test.go:280: With indices exec time: 11.647093789s
universe_perf_test.go:289: Improvement: 2.49x
```
I also confirmed on mainnet that the old and new query return the exact same result:
[old-query.txt](https://github.com/user-attachments/files/18479924/old-query.txt)
[new-query.txt](https://github.com/user-attachments/files/18479925/new-query.txt)
The speedup on mainnet is also quite significant. The old query took 2.5 minutes while the new one only took 15 seconds.
Hopefully this should make …

tapdb: fix performance of aggregate stats

---

monitoring/asset_balances_collector.go
monitoring/asset_collector.go
monitoring/config.go
monitoring/db_collector.go
monitoring/prometheus.go
sample-tapd.conf

This PR exports the prometheus collector timeout as a prometheus config parameter.
With this timeout we will be able to observe values on our loadtest tapds for longer periods, as the timeout will be harder to reach.

monitoring: export collector timeout as prometheus config

---

tapdb/universe_stats.go
tapdb/universe_stats_test.go

Our universe stats could run into a case where if in an un-cached state (like on system start-up) the db query takes longer than the default client timeout (usually 30s) then we'd fail the query and return early. This would cause the next client to also receive an error instead of the cached result, making this codepath stuck in an endless failing query. With this change we parallelize the db query and we always wait for the result in order to store it in cache. We may fail the function earlier, but the result will always be retrieved & persisted. This way, even if the 1st client retrieves an error, the next one will receive the cached (late) result of the previous run.
Closes https://github.com/lightninglabs/taproot-assets/issues/1304

Aggregate Universe Stats: always store result of querySyncStats

---

asset/asset.go
tapchannel/aux_invoice_manager.go
tapchannel/aux_invoice_manager_test.go

This PR adds an extra strictness check which requires the asset ID of the RFQ quote and HTLC records to match. This is done as an extra strict check to guard against HTLC and RFQ asset ID mismatch, which can lead to malicious behavior where a quote for a different asset is being accounted for when accepting an asset HTLC.
Closes https://github.com/lightninglabs/taproot-assets/issues/1255

Invoice Acceptor: ensure asset ID match between RFQ and HTLC 

---

.gitignore

Update `.gitignore` to exclude `itest` directory log files matching the pattern `.log.<num>.gz`.

gitignore: add rule to ignore btcd-itest log files

---

rpcserver.go
tapgarden/batch.go
tapgarden/caretaker.go
tapgarden/planter.go
tapgarden/planter_test.go

Changes are non-functional but should improve code clarity and robustness.
- enforce output count validation in `extractAnchorOutputIndex`  
- add nil check for group anchor validation  
- improve documentation for `PendingBatch` and `prepAssetSeedling`  
- refine rpc log messages for clarity

Cleanup Asset Minting Code in Preparation for Universe Commitments

---

itest/channels_test.go
rfqmsg/records.go
rfqmsg/records_test.go
tapchannel/aux_invoice_manager.go
tapchannel/aux_invoice_manager_test.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1321.

rfqmsg: detect asset related custom records correctly

---

tapchannel/commitment.go

Fixes more occurrences related to #1321.

tapchannel: detect asset related custom records correctly

---

tapchannel/aux_traffic_shaper.go

This lets other sub-systems determine if an HTLC is for a custom channel, without needing to know about the precise record types.

tapchannel: add new IsCustomHTLC method to aux traffic shaper

---

server.go
tapchannel/aux_traffic_shaper.go

Follow-up for https://github.com/lightninglabs/taproot-assets/pull/1334.
The Server struct needs to implement all the interfaces for litd.

server+tapchannel: move IsCustomHTLC method

---

address/encoding.go
address/records.go
asset/records.go
itest/assertions.go
itest/asset_meta_test.go
itest/utils.go
proof/backward_compat_test.go
proof/meta.go
proof/proof_test.go
rpcserver.go
tapdb/addrs.go
tapdb/asset_meta.go
tapdb/asset_meta_test.go
tapdb/asset_minting.go
tapdb/assets_common.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/assets.sql
tappsbt/decode.go
tappsbt/encode.go

Extracted refactor and standalone fixes from https://github.com/lightninglabs/taproot-assets/pull/1335 so we can get them in earlier.

proof+tapdb: refactor and fix TLV unknown odd types bug for backward compatibility

---

tapdb/multiverse.go
tapdb/multiverse_cache.go

We tried to acquire the read lock after already having acquired the write lock.

tapd: fix mutex deadlock in universe cache

---

tapchannel/aux_invoice_manager_test.go

We include the asset specifier in the generated quotes of the property test framework. This is needed as now the aux invoice HTLC interceptor performs an extra check, according to which the asset ID in the rfq and the wire records must match.
PR #1299 introduced this check

tapchannel: add specifier in property test rfq generator

---

itest/tapd_harness.go
itest/test_harness.go
tapdb/multiverse.go

This time we activate the syncer cache by default in the integration tests to avoid further issues.
The actual bug fix is quite trivial, the wrong root node was inserted into the cache.

tapdb: fixes another issue with the syncer cache

---

itest/assets_test.go
itest/loadtest/config.go
itest/loadtest/load_test.go
itest/loadtest/loadtest-sample.conf
itest/loadtest/mint_batch_test.go
itest/test_harness.go
itest/utils.go

This is a lighter version of the mintTest, which also uses a few more configuration parameters to control how minting occurs. We now mint normal assets into a fixed total number of groups.
This was originally intended as a rewrite of the existing mint test, but it is introduced as a totally separate function. We could keep both functions and even try to run them in parallel at some point.
The minter is fixed to Alice node, as Bob could not mint into a group that is controlled by Alice. So fixing this role to Alice makes things much simpler.

Add `mintV2` loadtest

---

itest/loadtest/config.go
itest/loadtest/load_test.go
itest/loadtest/loadtest-sample.conf
itest/loadtest/send_test.go
itest/loadtest/utils.go
itest/utils.go

Based on #1285 
This PR adds the last 2 commits.
This PR adds a new refactored send test for our loadtest suite, `sendV2. 
The new send test uses normal assets which may have balances greater than `1` (case for collectibles), which offers a bit more coverage for our code (coin selection, psbt signing, etc).
Compared to the original send test, we strip away any non-mandatory assertions and RPC calls, keeping them to the minimum required to make things happen.

Add loadtest `sendV2`

---

Makefile
itest/chantools_harness.go

A new version of chantools is available. But we want to use a specific version, so we make sure to always build it for the itest to not interfere with any other version that might already be installed on the system.

make+itest: don't use locally installed chantools

---

itest/assertions.go
itest/asset_meta_test.go
itest/utils.go
proof/encoding.go
proof/meta.go
proof/meta_test.go
proof/mock.go
proof/proof_test.go
proof/records.go
proof/testdata/proof_tlv_encoding_generated.json
rpcserver.go
tapdb/addrs.go
tapdb/asset_meta.go
tapdb/asset_meta_test.go
tapdb/asset_minting.go
tapdb/assets_common.go
tapdb/migrations.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/migrations/000028_asset_meta_tlv_fields.down.sql
tapdb/sqlc/migrations/000028_asset_meta_tlv_fields.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/assets.sql
tapdb/sqlutils.go
tapgarden/batch.go
tapgarden/seedling.go
tappsbt/testdata/psbt_encoding_generated.json

~Depends on https://github.com/lightninglabs/taproot-assets/pull/1337.~
Fixes https://github.com/lightninglabs/taproot-assets/issues/956.
Adds two new fields to the TLV record of the asset's meta reveal:
- Decimal display: Allows minting of assets with non-JSON meta data as we don't need to rely on writing the field there)
- Canonical universe URL: Define the "home" universe for an asset that universe commitments will be synced to
**Important for reviewers**:
- This PR does not add the RPC or CLI level flags for the two new entries. Those only really make sense with https://github.com/lightninglabs/taproot-assets/pull/1325 merged as well, so we'll add those later.
- ~While writing this PR a bug was found in the backward compatible way we use odd TLV records. See …

proof: add new universe commitment TLV fields to asset meta reveal

---

scripts/check-go-version-yaml.sh

After running integration tests locally, the chantools repo is pulled, causing the linter to mistakenly analyze that repo. This commit updates the linter exclusion list to prevent this issue.

scripts: exclude ./itest/chantools from YAML Go version linter

---

rfq/mock.go
rfq/negotiator.go
rfq/negotiator_test.go
rfq/oracle.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1361  
This PR corrects a bug where we called the wrong price oracle endpoints when evaluating the price from a quote accept message sent in response to a quote request message.  
Additionally, we enhance the mock price oracle to allow method call hooking.  
See the commit messages for details on the original issue and the correct approach.

RFQ accept price qualify bug

---

rfq/negotiator.go
rfqmath/fixed_point.go
rfqmath/fixed_point_test.go

This PR enhances the documentation for `FixedPoint.WithinTolerance` to clarify that the tolerance check is max-based, meaning it is applied relative to the larger of the two values. This ensures that a 100% tolerance (1,000,000 PPM) always results in a match for any two nonzero values.  
Additionally, the function now returns an error if either value is zero, as tolerance is undefined in such cases.  
These are alternative strategies that we don't use in our code.
- **Bid-based (stricter):** Uses the smaller value as the reference. This enforces a tighter threshold but does not guarantee a match at 100% tolerance. It may also be more intuitive in some bid-ask spread scenarios, so it is something to keep in mind.  
- **Midpoint-based (balanced):** Uses the average of both values. This …

rfqmath: Improve WithinTolerance doc and handle zero coefficient edge case

---

rpcserver.go

Previously, callers of rfqChannel would just get the first channel from the list of candidates. This is sufficient, but we could easily optimise this depending on the intention. Depending on whether we want to receive or send over the channel, we return the channel with the best remote or local balance accordingly.

rpcserver: better rfq channel selection

---

fn/context_guard.go
rfq/negotiator.go

This PR introduces a **proof of concept** for `ContextGuard.Goroutine`, a method designed to simplify goroutine management within `ContextGuard`. It ensures consistent error handling via a dedicated error handler and manages the wait group automatically.  
To demonstrate its potential usefulness, this PR applies `ContextGuard.Goroutine` in to one spot in our RFQ code, showcasing how it can standardise error handling. This is an early iteration to explore whether this approach is handy for broader use.

Proof of Concept: Simplifying Concurrency with `ContextGuard.Goroutine`

---

.gitignore
Makefile
cmd/merge-sql-schemas/main.go
tapdb/sqlc/schemas/generated_schema.sql

In this PR, we introduce a new Go script located in
`cmd/merge-sql-schemas/main.go` that consolidates SQL migration files
into a single schema file. The script reads all `.up.sql` migration
files from the `tapdb/sqlc/migrations` directory, executes them in order
on an in-memory SQLite database, and retrieves the final schema
definitions for tables and views.
Additionally, the Makefile is updated to include a call to this new
script during the SQL code generation process. The `.gitignore` file is
that temporary or unwanted files do not clutter the repository.
also modified to exclude files matching the pattern `.aider*`, ensuring
When I was making #1386, I made a few mistakes along the way as I was looking at the _initial_ migration file, but later migration files ended up modifying a …

tapdb+sqlc: sqlc: add script to merge SQL migrations into consolidated schemas 

---

itest/utils.go
tapchannel/allocation.go
tapdb/asset_minting_test.go
tapgarden/batch.go
tapgarden/custodian_test.go
tappsbt/encode.go
tapscript/tx.go
tapscript/util.go

Replace redundant `PayToTaprootScript` function definitions with `txscript.PayToTaprootScript` to eliminate unnecessary duplicate code.

Remove redundant PayToTaprootScript functions

---

Makefile

https://github.com/lightninglabs/taproot-assets/pull/1387#discussion_r1961154190
Fixes incorrect removal of the sqlc target in #1387. Without this dependency, the check doesn't actually check anything.

make: fix sqlc-check

---

itest/assets_test.go
rpcserver.go
tapdb/assets_store.go
tapfreighter/chain_porter.go
tapfreighter/coin_select.go
tapfreighter/interface.go
tapfreighter/wallet.go
tapsend/send.go

Related to https://github.com/lightninglabs/taproot-assets/issues/1164
This PR simply implements the plumbing required to utilize the PrevIds payload for FundVirtualPSBT. Similar to how we can only handle 1 address for a raw input, this PR also only implements support for a single PrevId in the PrevIds payload.
At a high level, we perform the following:
- Update FundAddressSend() to take in an optional array of PrevID pointers
- If we see the PrevID pointers array is provided, and the length is 1, we add these values to the CommitmentConstraints object. CommitmentConstraints is also updated as a struct to hold an array of PrevIDs
- We update `constraintsToDbFilter` to utilize the prevID if the length is 1:
```
if len(query.PrevIDs) == 1 {
prevID := query.PrevIDs[0]
encodedOutpoint, err := …
```

Implement PrevId[] UTXO selection for FundVirtualPSBT RPC method; valid for single PrevId at first

---

itest/assertions.go
itest/utils.go
proof/append.go
proof/append_test.go
proof/archive.go
proof/archive_test.go
proof/backward_compat_test.go
proof/mint.go
proof/mint_test.go
proof/mock.go
proof/proof_stitching_test.go
proof/proof_test.go
proof/verifier.go
rpcserver.go
tapchannel/aux_funding_controller.go
tapchannel/aux_sweeper.go
tapdb/assets_store.go
tapdb/assets_store_test.go
tapdb/sqlutils_test.go
tapfreighter/chain_porter.go
tapgarden/caretaker.go
tapgarden/custodian.go
tapgarden/custodian_test.go
tapgarden/planter.go
tapgarden/re-org_watcher.go
tapsend/proof_test.go
tapsend/send_test.go
universe/base.go

In this PR, we introduce a new proof.VerifierCtx struct to cut down
on line noise when verifying single proofs and proof files. This also
lets us centralize the creation of the various interfaces we need to
verify a proof.
We then add a new interface, the IgnoreChecker. This is to be
used as a proof rejection cache, which allows us to ensure that we don't
continue to validate proofs that we already know to be invalid. The
underlying cache implementation is also intended to support its own
invalidation to handle re-org edge cases.

proof: add new IgnoreChecker proof rejection cache 

---

itest/loadtest/config.go
itest/loadtest/load_test.go
itest/loadtest/loadtest-sample.conf
itest/loadtest/sync_test.go
itest/loadtest/utils.go

This PR adds a new type of loadtest, which is focused around the syncing endpoints.
We add a new test that emulates a full `AssetRoots` sync by a configurable number of clients. The page size may also be configured (although I believe we better use the max).
Since the dummy syncers don't care about the actual data and all we're trying to do is stress the universe server, we don't even use a tap related client. We hit the public REST endpoint for simplicity and ignore the response's details.
Also added a TODO for future expansions and configurations for this test. For now, this test is only restricted to performing an AssetRoots sync from multiple clients (from the PoV of the server).
Closes #1313

Add `sync` loadtest

---

asset/asset.go
itest/rfq_test.go
itest/test_list_on_test.go
rfq/manager.go
rfqmsg/buy_request.go
rfqmsg/sell_request.go
rpcserver.go
tapcfg/server.go

This PR introduces the minimum functionality for two nodes to negotiate and register a buy or sell quote, which identifies the underlying asset via a group key instead of an ID.
It includes a basic itest which lets Alice & Bob negotiate a quote based on a specifier which only includes a group key.
Related to https://github.com/lightninglabs/taproot-assets/issues/1028, but does not close it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightninglabs/taproot-assets/1382)

Support group keys for RFQ negotiation flows

---

cmd/commands/commands.go

Adds ability to global flags to de config using ENV variables.
This is useful when running `tapcli` in containers and for any reason not using default values or running lightning-terminal in integrated mode.

tapcli: Global flags to accept ENV vars overrides.

---

proof/courier.go
proof/file.go
proof/proof.go
proof/proof_test.go
rpcserver.go
tapchannel/auf_leaf_signer_test.go
tapchannel/aux_funding_controller.go
tapchannelmsg/records_test.go
tapchannelmsg/wire_msgs_test.go
tapdb/assets_store.go
tapdb/assets_store_test.go
tapdb/sqlutils_test.go
tapdb/universe_test.go
tapfreighter/parcel.go
tapgarden/caretaker.go
tapgarden/planter.go
tappsbt/encode.go

Add method `Proof.Bytes` and then use in many places. Removes redundant buffer variable and two redundant standalone functions.

Add method `Proof.Bytes`

---

rpcserver.go
tapdb/burn_tree.go
tapdb/burn_tree_test.go
tapdb/ignore_tree.go
tapdb/ignore_tree_test.go
tapdb/multiverse.go
tapdb/sqlutils_test.go
tapdb/universe.go
tapdb/universe_federation.go
tapdb/universe_federation_test.go
tapdb/universe_test.go
tapgarden/caretaker.go
tapgarden/custodian_test.go
tapgarden/planter.go
universe/base.go
universe/interface.go

In this commit, we add a new interface, the BurnTree. This interface
will be used by a future sub-system to maintain the on-chain asset
commitment for a given asset group.
The structure of this tree is very similar to the existing issuance
tree. The main difference is that we'll only insert burn proofs into
this tree.
We then implement a concrete implementation of this interface 
using the existing universe tree routines.

tapdb+universe: implement new Universe tree for 1st party burns

---

mssmt/compacted_tree.go
mssmt/interface.go
mssmt/tree.go
mssmt/tree_test.go

In this commit, we add a new `Copy` method that takes as an arg another `mssmt.Tree` and inserts all the keys+leaves from the target tree into the source tree. We then optimize a bit by adding an `InsertMany` method that will call `insert` N times in the same `TreeStoreUpdateTx`. This doesn't yet implement any fancy optimizations to ensure the root is only updated once as https://github.com/lightninglabs/taproot-assets/pull/1347 does. 
This was spun off a work unit related to https://github.com/lightninglabs/taproot-assets/pull/1464.

mssmt: add new Copy method and InsertMany to optimize slightly 

---

rfq/manager.go
rfqmath/fixed_point.go
rfqmath/fixed_point_test.go
rpcserver.go
taprpc/tapchannelrpc/tapchannel.pb.go
taprpc/tapchannelrpc/tapchannel.proto
taprpc/tapchannelrpc/tapchannel.swagger.json

This PR allows for the user to set the invoice value via the `Value`/`ValueMsat` fields.
Previously we'd take the asset units and the agreed upon quote, then we'd convert that to an msat amount. Now the value of the invoice can be directly set via the previously ignored fields, while also still acquiring a sufficient quote and returning that to the user.
Closes #1440 
Fixes #1306

Allow setting sats/msats to `taprpc.AddInvoice`

---

tapdb/assets_store.go
tapdb/assets_store_test.go

Previously, QueryParcels did not populate the pkScript field of the anchor outputs. This commit addresses that issue.

tapdb: correctly fill pkScript for outputs of QueryParcels

---

chain_bridge.go
itest/utils.go
tapchannel/aux_funding_controller.go
tapfreighter/chain_porter.go
tapfreighter/interface.go
tapgarden/caretaker.go
tapgarden/interface.go
tapgarden/mock.go

This PR chanegs the label used for Txs published to the network. Before, *all* Txs got the label `tapd-asset-minting`. Now, the label depends on the context. Currently we use two labels:
- `tapd-asset-minting`
- `tapd-asset-send`
In the future we could even allow for more granular information being passed to the label.

multi: Add label to `PublishTransaction`

---

.github/workflows/main.yaml

Since the group-key-support branch was merged, we can use the master branch to run tests against.

GitHub: use master again for litd itests

---

.github/workflows/main.yaml
rfq/stream.go

Fixes https://github.com/lightninglabs/taproot-assets/issues/1460.
We store the outgoing request in the request map, so we can interpret any response and map it to the original request. We do this before sending the message, because otherwise we could potentially receive the response while we're waiting for the atomic lock to be released, which would lead to us not knowing about the request in the first place, and we couldn't map the response.

rfq: store outgoing request before sending message

---

tapchannel/aux_closer.go
tapchannel/commitment.go
tapsend/allocation.go

What this issue fixes is a bit hard to explain. So I'll just copy the comment that's above the fix:
```golang
// [...] When we [coop] close a channel, the output of the
// `lncli closedchannels` command will show the last commitment state of
// the channel as the closing asset balance. Which is correct in terms
// of balances. But if there are multiple different asset IDs (e.g., in
// a grouped asset channel), then _how_ those pieces are distributed
// within the commitment transaction depends on the order of the
// allocations. And the order of the allocations is dependent on the
// BTC amount and the pkScript of the BTC-level output. Both of which
// are different in the coop close output (we set the asset-level output
// BTC amount to the dummy amount, and the pkScript will be a newly …
```

channels: fix coop close asset distribution for grouped asset channels

---

rfq/manager.go
rpcserver.go

Fixes an issue reported on Slack:
```
2025-05-01 11:41:02.817 [ERR] RPCS: [/tapchannelrpc.TaprootAssetChannels/SendPayment]: error adding sell order: error marshalling sell order response: unknown AddAssetSellOrder event type: *rfq.PeerAcceptedBuyQuoteEvent
```
This happens when two orders of different types are added at more or less the same time, then we receive the wrong one on the subscriber channel.
So we need to filter by type and also by matching the order to the returned quote event.

rfq+rpcserver: match event to order

---

monitoring/monitoring_on.go

Closes https://github.com/lightninglabs/taproot-assets/issues/1495
---
Default bucket sizes top out at 10s, causing longer-running RPC calls to be grouped into the largest bucket. This commit adds more buckets to provide finer-grained visibility into endpoint latency.
Terminal Web team report that a unary endpoint took 45mins to run one day and 4mins the next. We should be able to track that sort of variability.

monitoring: expand Prometheus buckets for RPC endpoint latency

---

itest/assertions.go
itest/send_test.go
itest/tapd_harness.go

Move the context definition inside the retry loop to create a new timeout context for each attempt. Set the retry period to double the instance context timeout to enable multiple attempts.
---
Attempts to fixes this CI postgres itest flake:
```
2025-04-28 14:51:34.847 [INF] GRDN custodian.go:923: Received new proof file for asset ID c01c916edf128edcbed0421cf38e3dbbf5dc9de4f382befc49f54780ac88882d, version=0,num_proofs=3
2025-04-28 14:51:34.938 [INF] PROF courier.go:657: Starting proof transfer backoff procedure (transfer_type=send, locator_hash=ada130e14fbcff36f1267894e7a5721aba049f5bf115d8d02ed2bd32e2521ea4)
2025-04-28 14:51:34.963 [INF] FRTR chain_porter.go:973: Transfer output proof delivery complete (anchor_txid=2adf9b2f964c5376f2c7035274daa7a0931ce7810383da5a2cceb9cbfaaba82c, …
```

fix itest flake: allow AssertNonInteractiveRecvComplete more time to execute

---

rpcserver.go

Close: https://github.com/lightninglabs/taproot-assets/issues/1531
---
Updates the SendPayment RPC to return immediately upon receiving a payment failure update. This avoids unnecessary waiting for a context timeout or quit signal.

rpcserver: stop SendPayment update stream when payment fails

---

itest/assets_test.go
tapgarden/planter.go
taprpc/mintrpc/mint.pb.go
taprpc/mintrpc/mint.proto
taprpc/mintrpc/mint.swagger.json

Closes: https://github.com/lightninglabs/taproot-assets/issues/1535
---
This PR fixes a bug in `ListBatches` where a single nil element was left in the `verboseBatches` list, causing a panic during RPC marshalling. The bug occurred when a single unfunded pending batch was present.
Changes:
* Set `verboseBatches` length to zero to avoid uninitialized elements.
* Add a comment explaining why funding is required for verbose batch info.
* Add an itest to cover this edge case.
* Improve proto documentation for the `verbose` field in `ListBatches`.

Fix panic when listing unfunded pending batch with verbose

---

tapchannel/aux_closer.go
tapchannel/commitment.go
tapsend/allocation_test.go

This partially reverts commit 3ed142ffdc59f53a3d405b960f5d24641c5cc51c to restore backward compatibility with nodes running on v0.5.x.
The intention with removing this explicit split root assignment was to simplify the code. But it actually would lead to force closes between nodes on v0.6.0 and v0.5.x, because they wouldn't be able to agree on what output should be chosen for the split root (since the behavior was changed).

tapchannel: don't break backward compatibility

---

rfq/manager.go
rfq/manager_test.go
rpcserver.go
tapcfg/server.go
tapchannel/aux_invoice_manager.go
tapchannel/aux_invoice_manager_test.go
taprpc/tapchannelrpc/tapchannel.proto
taprpc/tapchannelrpc/tapchannel.swagger.json
taprpc/tapchannelrpc/tapchannel_grpc.pb.go
wallet_anchor.go

This PR introduces the ability for tapd nodes to create invoices which involve multiple peer quotes. When the `peerPubKey` is left unspecified in the `AddInvoice` RPC we no longer return an error, but instead acquire quotes with all peers that have a valid asset channel with us.
Within this PR we also extract some rfq/liquidity related functions to the `rfq` package to keep `rpcserver.go` more clean.
Closes #1359 
Based on #1423 (using that as base branch for now to avoid bloated diff)

Multi rfq receive (`AddInvoice` multiple hop hints)

---

tapgarden/planter_test.go

The `unit-race` CI job frequently flakes due to test timeouts. Raising the default timeout to 30s should help reduce these flakes without noticeably slowing down the unit tests.
Two example failed CI runs:
```
--- FAIL: TestBatchedAssetIssuance (54.87s)
test_sqlite.go:11: Creating new SQLite DB handle for testing: /tmp/TestBatchedAssetIssuance904633052/001/tmp.db
--- FAIL: TestBatchedAssetIssuance/basic_asset_creation (12.75s)
planter_test.go:1153: 
Error Trace:	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:1023
/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:1153
/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:2048
Error:      	Received unexpected error:
timeout hit
Test: …
```

tapgarden: increase unit test default timeout from 10s to 30s

---

rpcserver.go

Fixes https://github.com/lightninglabs/lightning-terminal/pull/1075#pullrequestreview-2853005100.
If the user specifies sats but we end up setting the (validated) mSat amount, we run into the error "sat and msat arguments are mutually exclusive" in lnd.
To fix that, we need to reset the sat value.

rpcserver: fix "mutually exclusive" err when using sats

---

proof/append.go
proof/mint.go
proof/verifier.go
proof/verifier_test.go
tapchannel/aux_closer.go
tapchannel/aux_funding_controller.go
tapchannel/aux_sweeper.go
tapchannel/commitment.go
tapsend/proof.go

Because we do not bump the proof version yet, but we still create v1
proofs, we at least verify them if they are present.
This was the state table for choosing which verification would occur before this PR:
|    | hasStxoProofs<br><br>IsTransferRoot | hasStxoProofs<br><br>!IsTransferRoot | !hasStxoProofs<br><br>IsTransferRoot | !hasStxoProofs<br><br>!IsTransferRoot |
|----|-------------------------------------|--------------------------------------|--------------------------------------|---------------------------------------|
| V0 | verifyV0                            | verifyV0                             | verifyV0                             | verifyV0                              |
| V1 | verifyV0, verifyV1            | verifyV0                             | ERR …

proof: verify stxo proofs if present in v0 proofs

---

chain_bridge.go
fn/retry.go
fn/retry_test.go

This PR fixes #1562 by implementing automatic retry logic with exponential backoff for all block and header fetching operations in the chain bridge.
Along the way, we introduce a generic `RetryFuncN` function in the `fn` package that wraps any fallible operation with configurable retry logic featuring:
- Exponential backoff to avoid overwhelming the backend
- Context cancellation support for clean shutdown
- Configurable retry parameters (count, delays, backoff multiplier)
The retry wrapper is then applied to all key RPC operations in `chain_bridge.go`:
- `GetBlock` - Ensures we can always fetch full block data
- `GetBlockHeader` - Ensures header retrieval succeeds
- `GetBlockHash` - Ensures height-to-hash lookups work
- `CurrentHeight` - Ensures chain tip queries succeed
- …

 chain_bridge+fn: add retry logic for RPC calls to improve reliability in load-balanced environments

---

go.mod
rpcserver.go
tapchannel/commitment.go

Fixes root cause of https://github.com/lightninglabs/taproot-assets/issues/1595.
Also fixes https://github.com/lightninglabs/taproot-assets/issues/1598.
Corresponding integration tests can be found here: https://github.com/lightninglabs/lightning-terminal/pull/1089

bugfix: fix btc-only balance force close, fix incorrect policy in invoice hop hint

---

proof/proof_test.go
universe/proof_download_test.go

This commits the code that was used to create manually repaired proofs here: https://github.com/lightninglabs/taproot-assets/issues/1595#issuecomment-2977890999
This might come in handy in the future to rescue funds from borked asset channels.

proof: add debug utilities for manually fixing proofs

---

itest/channels_test.go
rpcserver.go

Fixes an issue where attempting to pay a below-dust carrier HTLC satoshi amount would knock a channel offline.
Found after attempting the negative test mentioned here: https://github.com/lightninglabs/lightning-terminal/pull/1089#discussion_r2150457951
Nice catch, @GeorgeTsagk.

rpcserver: enforce keysend minimum carrier HTLC amount

---

tapdb/postgres.go
tapdb/postgres_test.go
tapdb/sqlerrors.go

In this PR, we start to sanitize unexpected DB errors before returning to the caller. This is important, as ultimately for our gRPC calls, the caller is some client-side software. For now, we take the simple approach and match on some obvious strings, mapping them to a generic "db connection failed" error.

tapdb: sanitize db errors before returning

---

tapdb/asset_minting.go
tapdb/asset_minting_test.go
tapdb/migrations.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/migrations/000041_seedling_uni_commit.down.sql
tapdb/sqlc/migrations/000041_seedling_uni_commit.up.sql
tapdb/sqlc/models.go
tapdb/sqlc/queries/assets.sql
tapdb/sqlc/schemas/generated_schema.sql

This is part of the work towards completing https://github.com/lightninglabs/taproot-assets/issues/1534
---
* Store and fetch delegation key references to/from the `asset_seedlings` table.
* Add support for persisting the universe commitment flag in both `asset_seedlings` and `minting_batches`.
* Add unit tests to verify flag round-trips correctly through the DB.
* **Other:**
* Remove dependency on `ChangeOutputIndex` when deriving asset anchor output index.

tapdb: support delegation key and universe commitment flag in seedlings

---

.github/workflows/main.yaml
asset/asset.go
asset/records.go
itest/addrs_test.go
itest/assertions.go
itest/test_list_on_test.go

Attempt to fix a flaky test: [GitHub Actions Run](https://github.com/lightninglabs/taproot-assets/actions/runs/16271389499/job/45942931750?pr=1643)
This change updates `AssertBalanceByID` to use an eventually-style assertion. This should eliminate timing-related flakiness by allowing for retries within a time window. While this may not fully resolve the issue, it helps rule out timing as a contributing factor.

itest: convert AssertBalanceByID to eventually-style call

---

address/book.go
address/book_test.go
chain_bridge.go
rpcserver.go
tapdb/addrs.go
tapdb/sqlc/assets.sql.go
tapdb/sqlc/querier.go
tapdb/sqlc/queries/assets.sql

It turns out it's not actually the stats query itself that is slow but the two pieces of information we need to fetch for each asset returned in the result:
- The genesis timestamp: Needs to be fetched by looking up a block in the chain backend. Is already cached, but we increase the cache. https://github.com/lightninglabs/taproot-assets/blob/eff99b84184dbe72dccdbcafb6915e07e76572f2/rpcserver.go#L6545
- The decimal display value: We used to do a DB lookup for each asset (which takes forever with a cardinality of ~100k on mainnet). We now cache this. https://github.com/lightninglabs/taproot-assets/blob/eff99b84184dbe72dccdbcafb6915e07e76572f2/rpcserver.go#L6551

universe: fix asset stats being extremely slow

---

tapchannel/aux_invoice_manager.go
tapchannel/aux_traffic_shaper_test.go

When converting an mSAT amount to units and vice versa we frequently get an off-by-1-unit result. This is already accounted for in our invoice acceptor by adding the value of as many asset units as HTLCs in the invoice. What we didn't account for is that the UnitsToMilliSatoshi calculation for the margin can also be off by 1 msat.
So the result of `UnitsToMilliSatoshi` for the `totalUnits - 1` can itself be off by 1mSAT, compared to the result of `UnitsToMilliSatoshi` for a single unit

tapchannel: add a one unit extra tolerance to invoice acceptor

---

internal/ecies/ecies.go

This PR updates the HKDF parameters used in ECIES encryption to improve key derivation security:
- The per-message nonce is now used as the `salt` input to `HkdfSha256`. This improves brute-force resistance by introducing entropy that changes with each encryption.
- The protocol name, previously used as a constant salt, is now passed as the `info` parameter. This better aligns with the intended purpose of `info`, which is to provide domain/context separation.
Using a random, per-message salt ensures that the derived keys are unique even if the input key material is reused or predictable, and prevents pre-computation attacks. The change follows HKDF best practices.

Use nonce as HKDF salt and protocol name as info in ECIES encryption

---

itest/tapd_harness.go

Fixes a flake where uploading proofs to the proof courier would take more than 50 milliseconds in CPU constrained environments such as CI.

itest: increase proof courier timeout

---

docs/debug-handbook/README.md
docs/debug-handbook/psbt-finalization-failures.md
docs/debug-handbook/psbt-quick-reference.md

In this PR, we add a README for a new area of documentation intended
for active developers of the project. The goal of this new set of docs
is to capture all the hard earned wisdom that devs gain while debugging
a non-trivial issue. It's meant to serve as a run book to allow for
rapid pattern matching to identify a routine issue, along with a guided
path to aide in debugging.
This should also be great for agents as well, since they can use them to
locate issues that they would otherwise need some prodding to figure
out.
The first one added is intended to devs find PSBT signing related issues more quickly. I ran into this during the dev of https://github.com/lightninglabs/taproot-assets/pull/1675 to get the itests working properly. It relies on some deeper knowledge of: PSBTs, the way lnd …

docs/debug-handbook: create new debug run books for developers to help pattern match common issues and knowledge

---

docs/release-notes/release-notes-0.7.0.md
tapchannel/aux_invoice_manager.go
tapchannel/aux_traffic_shaper_test.go

First commit exposes our current tolerance, leading to new rounding errors.
There was also an inaccuracy in the way we sharded the amount across the number of HTLCs. We had to also carry the remainder of `invoiceAmt / numHTLCs`, which is currently added to the last shard.
Then we modify the tolerance model to instead be `(1unit + 1msat)*numHTLCs`
Let's use this topology to put things in order
```
Alice --[units]--> Bob --[msat]--> Carol --[units]--> Dave 
```
Dave creates an asset invoice, Alice pays to it (with `N` HTLCs)
- When an HTLC is forwarded to Carol: Carol converts msats to units, this justifies `N units` of tolerance
- When an HTLC is received by Dave: Dave converts the units of the HTLC back to msats, as the invoice is measured in msats, this justifies `N msats` of tolerance …

Invoice manager tolerance tweaks

---

tapdb/addrs.go

Return early when the `StartTimestamp` is set in the future, so no events can be returned.

itest: fix address receives test: timestamp in the future

---

docs/release-notes/release-notes-0.7.0.md
itest/supply_commit_test.go
tapdb/supply_commit.go
tapdb/universe.go
tapdb/universe_test.go
universe/supplycommit/env.go
universe/supplycommit/mock.go
universe/supplycommit/state_machine_test.go
universe/supplyverifier/manager.go
universe/supplyverifier/mock.go
universe/supplyverifier/transitions.go
universe/supplyverifier/util.go
universe/supplyverifier/util_test.go
universe/supplyverifier/verifier.go

Closes: https://github.com/lightninglabs/taproot-assets/issues/1811
This PR adds functionality to extract supply pre-commits directly from the mint leaves retrieved by the supply verifier during a sync pull of a supply commitment.
Previously, the supply verifier relied on the universe issuance syncer to obtain the full set of pre-commitments. This change removes that dependency, reducing the risk of a race condition where supply commitments were synced before the associated pre-commitments were available.

Extract supply pre-commits from mint leaves during supply verifier sync

---

docs/release-notes/release-notes-0.7.0.md
tapdb/migrations.go
tapdb/migrations_test.go

This PR fixes 2 issues in the current handling of database migrations in `tapdb`:
1. The main issue resolved is that we add a check during startup to ensure that the database version is not dirty (i.e., the last migration did not complete successfully). If it is dirty, the application will now always exit with an error.
This is done to resolve a bug that would occur when the migration with the  **latest** migration version failed. In that scenario, the database version would correctly be marked as dirty and exit with an error. However, under `sqlite` database backends, when `tapd` was restarted, the dirty database version would never be checked and `tapd` would start up normally, despite the database being in a dirty state. This is due to the check here: …

tapdb: error on dirty database versions
