lightninglabs/taproot-assets

cmd/tarocli/main.go, cmd/tarocli/proofs.go
Fixes https://github.com/lightninglabs/taro/issues/141 and two general bugs in the CLI.
=> cmd: fix import/export from file, allow stdin/stdout to be used

proof/courier.go, tarofreighter/chain_porter.go, tarogarden/custodian.go
The second commit is a bug fix as otherwise, we'd time out when doing the final step of a transfer. The other commits are left over review comments from #132.
=> mutli: fix surpuious timeout due to incorrect quit/wait usage, make usage more consistent 

.gitignore
Similar to[ LND gitignore.](https://github.com/lightningnetwork/lnd/blob/master/.gitignore#L66-L67)
=> gitignore: ignore IDEA editor config

dev.Dockerfile, docs/docker.md
=> Add Docker Support

.github/actions/setup-go/action.yml, .github/workflows/main.yaml
This PR refactors the CI pipeline and also bumps action version numbers.
It also introduces a new action which sets up the go environment.
=> ci: refactor and bump actions

tapfreighter/chain_porter.go, tapfreighter/parcel.go
In this commit, we ensure that pending parcels are resumed using the same goroutine that processes the normal send parcel processing flow.
The goal of this change is to ensure that the locking mechanism enforced by a singular parcel processing goroutine is not compromised by the execution of a secondary parcel goroutine.
=> tapfreighter: resume pending parcels using the main porter goroutine

cmd/tapcli/main.go, cmd/tapcli/proofs.go
Fixes https://github.com/lightninglabs/taproot-assets/issues/341.
=> cmd/tapcli: add asset ownership proof sub commands

asset/asset.go, proof/mint.go, proof/proof.go, proof/proof_test.go, proof/verifier.go
Replaces #448 using a branch on this repo and with the correct base branch.
=> Proof: genesis reveal + and groupkey reveal validation

fn/func.go, rpcserver.go, tapfreighter/interface.go, tapfreighter/parcel.go, tapfreighter/wallet.go
A couple of commits extracted out of https://github.com/lightninglabs/taproot-assets/pull/477 that don't necessarily have to do with burning itself.
Fixes https://github.com/lightninglabs/taproot-assets/issues/414.
=> Small fixes in freighter and wallet

rpcserver.go
Make sure that we check that we check that req fields are not null before accessing them.
=> rpcserver: validate rpc requests

address/address.go, address/address_test.go, address/encoding.go, address/mock.go, address/records.go, address/testdata/address_tlv_encoding_generated.json
Closes https://github.com/lightninglabs/taproot-assets/issues/500
=> Add version field to Tap address

tapgarden/custodian.go
Closes https://github.com/lightninglabs/taproot-assets/issues/513
=> tapgarden: pre proof retrieval delay respects context done signal

asset/asset.go, asset/asset_test.go, proof/verifier.go, rpcserver.go, tapgarden/seedling.go
Closes https://github.com/lightninglabs/taproot-assets/issues/506
Closes https://github.com/lightninglabs/taproot-assets/issues/523
=> Sanitise asset name

version.go
=> build: bump version to v0.3.0-alpha

cmd/tapcli/addrs.go, cmd/tapcli/main.go, itest/loadtest/utils.go, itest/tapd_harness.go, rpcserver.go, server.go, tapcfg/config.go, universe_rpc_registrar.go
Fixes https://github.com/lightninglabs/taproot-assets/issues/608.
=> multi: add proof courier addr to CLI, fix gRPC max message size, fix linter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Updates issue templates so that they match those found in the LND repository.
=> github: use the same issue templates as those found in LND repository

rpcserver.go
If we have the meta reveal present on a proof, we don't need to look up the meta data in the local DB.
Bug reported in Slack by a user, thanks a lot!
=> rpcserver: skip local meta data lookup for genesis proof

rfq/manager.go, rfq/negotiator.go, rfq/oracle.go, rfq/order.go, rfqmsg/accept.go, rfqmsg/buy_accept.go, rfqmsg/buy_accept_test.go, rfqmsg/buy_request.go, rfqmsg/buy_request_test.go, rfqmsg/messages.go, rfqmsg/reject.go, rpcserver.go
Towards fixing https://github.com/lightninglabs/taproot-assets/issues/818
This PR refactors the RFQ system to make adding asset sale support easier.
=> Refactor the RFQ service to handle payment init via asset sale

asset/asset.go, itest/multi_send_test.go, itest/test_list_on_test.go, rpcserver.go, tapfreighter/chain_porter.go, tapfreighter/parcel.go, tapfreighter/wallet.go, tappsbt/interface.go, taprpc/assetwalletrpc/assetwallet.pb.go, taprpc/assetwalletrpc/assetwallet.proto, taprpc/assetwalletrpc/assetwallet.swagger.json, taprpc/assetwalletrpc/assetwallet_grpc.pb.go
Depends on https://github.com/lightninglabs/taproot-assets/pull/796.
Fixes https://github.com/lightninglabs/taproot-assets/issues/754.
Fixes https://github.com/lightninglabs/taproot-assets/issues/670.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lightninglabs/taproot-assets/821)
=> [psbt saga 5/4]: Anchor multiple virtual transactions

.github/workflows/main.yaml, .github/workflows/release.yaml, Dockerfile, Makefile, asset/asset.go, asset/records.go, dev.Dockerfile, fn/option.go, go.mod, itest/loadtest/Dockerfile, make/builder.Dockerfile, proof/encoding.go, proof/mint.go, proof/proof.go, rpcserver.go, server.go, tapcfg/server.go, tappsbt/create.go, taprpc/Dockerfile, taprpc/marshal.go, tools/Dockerfile
This PR contains commits extracted from the lightning channel proof-of-concept (PoC) branch, focusing solely on code refactoring without introducing new functionality.
The objective of this PR is to advance the integration of PoC changes into the main codebase.
=> Lightning channel proof-of-concept refactor commits

itest/assertions.go, itest/asset_meta_test.go, itest/utils.go, proof/meta.go, rpcserver.go, tapdb/asset_minting.go, tapgarden/batch.go, tapgarden/interface.go, tapgarden/planter.go, tapgarden/seedling.go, taprpc/taprpc_utils.go
Addresses #948 .
The meta helpers need some unit tests.
=> Precision field checking

version.go
Leaving in draft until these PRs are merged:
* https://github.com/lightninglabs/taproot-assets/pull/971
* https://github.com/lightninglabs/taproot-assets/pull/973
* https://github.com/lightninglabs/taproot-assets/pull/975
=> build: bump version to v0.4 rc1

cmd/tapcli/universe.go, perms/perms.go, rpcserver.go, taprpc/universerpc/universe.pb.go, taprpc/universerpc/universe.pb.gw.go, taprpc/universerpc/universe.pb.json.go, taprpc/universerpc/universe.proto, taprpc/universerpc/universe.swagger.json, taprpc/universerpc/universe.yaml, taprpc/universerpc/universe_grpc.pb.go
Addresses #989 .
I'm not sure if exposing the endpoint with a `/push` suffix in the best option; maybe it doesn't make sense to expose over REST at all.
Testing manually now.
=> taprpc+tapcli: add universe proof push command

version.go
Will merge this after https://github.com/lightninglabs/taproot-assets/pull/101 is in.
=> version: bump version to v0.4.0-alpha.rc4

tapchannel/commitment.go
Fixes the last item described in https://github.com/lightninglabs/taproot-assets/issues/1019.
Validation integration test here: https://github.com/lightninglabs/lightning-terminal/pull/796.
This fixes a bug that lead to a panic in the following edge case:
- The initiator doesn't have any asset balance (everything was moved to the responder).
- An HTLC is created that sends some assets back to the initiator.
The problem that created is that because the initiator doesn't have any non-HTLC balance, no allocation was created with SplitRoot=true, which lead to a nil pointer panic in the logic that extracts the split root locator when creating a split commitment.
This commit fixes the problem by assigning the first HTLC that pays to the initiator with SplitRoot=true, if the initiator has zero …
=> tapchannel: fix split root when initiator has 0 balance

docs/examples/basic-price-oracle/go.mod, docs/examples/basic-price-oracle/go.sum, go.mod, go.sum, version.go
=> release: bump lnd to final v0.18.4-beta version, bump tapd version to v0.5.0-alpha

docs/examples/basic-price-oracle/main.go
Closes https://github.com/lightninglabs/taproot-assets/issues/1385
Add explanation of the difference between real-world prices and tap asset rates, and relate to asset decimal display. Also include a FixedPoint representation example to improve clarity.
=> basic-price-oracle: clarify price oracle demo asset rate documentation

docs/rfq_architecture.md
Tried to make this one very comprehensive, but it can likely be split up into smaller docs.
=> docs: add docs on e2e RFQ arch
